### ISSUE TITLE
Supported input formats

### ISSUE THREAD

**Issue by hazcod** [HaveAGitGat/Tdarr_Plugins#1]
Hi,

Love the idea, but what are the supported input formats? VIDEO_TS too?

**Comment by HaveAGitGat** [comment]
Thanks for taking a look! I haven't tried with VIDEO_TS folders but I don't think they'd work as media needs to be contained within a single file. I'll give it a try when I get some time.

**Comment by HaveAGitGat** [comment]
Sorry this is not suppported at the moment.
