### ISSUE TITLE
[Tdarr_Plugin_MC93_Migz5ConvertAudio] Does not convert PCM 2.0 to AAC

### ISSUE THREAD

**Issue by reloxx13** [HaveAGitGat/Tdarr_Plugins#104]
Heya,

recently i got some files with PCM 2.0 Audio which are very huge. I tried to convert them with Tdarr an the plugin `Tdarr_Plugin_MC93_Migz5ConvertAudio` but it does not convert them.

```
    Codec PCM
    Kanäle 2
    Bitrate 2302 kbps
    Sprache Deutsch
    Bit Depth 24
    Profil pcm_s24le
    Sampling Rate 48000 Hz
    Display Title Deutsch (PCM Stereo)
    Extended Display Title Deutsch (PCM Stereo)
```

Tdarr just shows this in I
```
Tdarr_Plugin_lmg1_Reorder_Streams - Pre-processing
File is not video
Tdarr_Plugin_MC93_Migz3CleanAudio - Pre-processing
☒File is not video
Tdarr_Plugin_076a_re_order_audio_streams - Pre-processing
☒ No audio tracks in desired language!
Tdarr_Plugin_MC93_Migz4CleanSubs - Pre-processing
☒File is not video
Tdarr_Plugin_b39x_the1poet_surround_sound_to_ac3 - Pre-processing
☒File is not video
Tdarr_Plugin_MC93_Migz5ConvertAudio - Pre-processing
☒File is not video.
Tdarr_Plugin_MC93_Migz1FFMPEG - Pre-processing
☒File is not a video. 
```

And this in H:
```
hevc | video | - | jpn | -
-- | -- | -- | -- | --
pcm_s24le | audio | 2.197 Mbs | ger | -
pcm_s24le | audio | 2.197 Mbs | jpn | -
hdmv_pgs_subtitle | subtitle | - | ger | -
hdmv_pgs_subtitle | subtitle | - | ger | -
```

**Comment by Migz93** [comment]
Your file has an issue that is causing almost all plugins to skip it with the message "File is not a video".
I can't remember which it is but try one of these plugins as the first plugin:
Tdarr_Plugin_MC93_Migz6OrderStreams.js
Tdarr_Plugin_MC93_MigzImageRemoval.js 

It should hopefully fix Tdarr being unable to identify the file correctly which will allow all the plugins to work.
If that doesn't work then search for the file in tdarr, click info and it should give you an output with all the files stream info, copy to pastebin and link here.

**Comment by reloxx13** [comment]
I have the default Tdarr reorder plugin at Top.

VLC also shows the HEVC Video is at firs
![grafik](https://user-images.githubusercontent.com/14855001/96420946-6f305e80-11f6-11eb-8d2d-0ad528c52dab.png)



This is my stack with both of your named plugins added now:
```
Community,Tdarr_Plugin_lmg1_Reorder_Streams,,
Community,Tdarr_Plugin_MC93_MigzImageRemoval,,
Community,Tdarr_Plugin_MC93_Migz6OrderStreams,,
Community,Tdarr_Plugin_drdd_standardise_all_in_one,,
Community,Tdarr_Plugin_MC93_Migz3CleanAudio,,
Community,Tdarr_Plugin_076a_re_order_audio_streams,,
Community,Tdarr_Plugin_MC93_Migz4CleanSubs,,
Community,Tdarr_Plugin_b39x_the1poet_surround_sound_to_ac3,,
Community,Tdarr_Plugin_MC93_Migz5ConvertAudio,,
Community,Tdarr_Plugin_MC93_Migz1FFMPEG,,
Community,Tdarr_Plugin_z18s_rename_files_based_on_codec,,
```

Ill let it run now

**Comment by reloxx13** [comment]
No change after all

Pastebin FIle Info from Tdarr: https://pastebin.com/bMG63iBM

**Comment by Migz93** [comment]
Your issue looks to be that `  "fileMedium": true,` in your info, a lot of plugins check that "fileMedium" = "video" which yours isn't, hence the file is getting skipped.

Will need to wait on GitGat to have a look and see why ffprobe seems to be picking that up wrong. The only thing I can think to try is run a "Scan (Fresh)" on that library to see if it can scan it again and pick up the fileMedium correctly.

**Comment by HaveAGitGat** [comment]
This has probably been fixed since then, reopen if needed
