### ISSUE TITLE
[Tdarr_Plugin_MC93_Migz1FFMPEG_CPU] Not escaping certain special characters in file name

### ISSUE THREAD

**Issue by gavzey** [HaveAGitGat/Tdarr_Plugins#121]
@Migz93 I just want to say that you've done some excellent work here, providing community plugins for all sorts of use cases, so thank you.

When processing files with certain special characters in the path, there is a missing closing quote in the source path which is causing processing to fail. 
I'm not sure exactly what's going on but I assume the path is being truncated at the unescaped special characters (namely commas and apostrophes).

Please let me know if you need any more information to help diagnose this issue.

Examples below:

` ffmpeg -y -i '/mnt/nas/Videos/TV/Modern Family (2009)/Season 02/Modern Family - 2x12 - Our Children, Ourselves - Bluray-1080p - x264 DTS.mkv' -map 0:2 "/mnt/nas/Videos/TV/Modern Family (2009)/Season 02/Modern Family - 2x12 - Our Children '/temp/Modern Family - 2x12 - Our Children, Ourselves - Bluray-1080p - x264 DTS-TdarrCacheFile-IlCOgkhdZ.mkv'
Last 200 lines of CLI log:
shellThread
/bin/sh: 1: Syntax error: Unterminated quoted string`

`/Kids/Lion King '/temp/Lion King, The (1994) - Bluray-1080p - x265 HDR-TdarrCacheFile-R9HuUw6oT.mkv'
Last 200 lines of CLI log:
shellThread
/bin/sh: 1: Syntax error: Unterminated quoted string`

**Comment by HaveAGitGat** [comment]
I believe this issue was fixed earlier this year but please reopen if needed.
