### ISSUE TITLE
nvenc plugins  incompatible with new encoders

### ISSUE THREAD

**Issue by minilandl** [HaveAGitGat/Tdarr_Plugins#122]
it seems nvenc plugins are incompatible with new encoders 

I have tried multiple nvenc plugins e.g  Tdarr_Plugin_d5d3_iiDrakeii_FFMPEG_NVENC_Tiered_MKV they all give the following errors about two pass encoding however I am able to use a simple ffmpeg nvenc plugin which I have created just fine so maybe these plugins need to be updated.

```
[hevc_nvenc @ 0x557536f6b1c0] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set

Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**Comment by supersnellehenk** [comment]
It isn't incompatible, the presets are different for the modes they're using. They aren't P1-P7, but words like fast, medium, slow, etc.

**Comment by Enigma0** [comment]
Seeing the same issue myself.

**Comment by supersnellehenk** [comment]
This should be fixed now, `-rc vbr_hq` got removed from plugins.
