### ISSUE TITLE
Plugin [Tdarr_Plugin_drdd_standardise_all_in_one] throws typeError in v2

### ISSUE THREAD

**Issue by guipace** [HaveAGitGat/Tdarr_Plugins#125]
Plugin throws error at the end of the transcode task.

Plugin ID: Tdarr_Plugin_drdd_standardise_all_in_one
Plugin Name: DrDD H265 MKV AC3 audio subtitles [QSV & NVENC]

Error message: "File is not video Tdarr_Plugin_drdd_standardise_all_in_one - Pre-processing ☒Plugin error! TypeError: Cannot read property 'streams' of undefined"

See link below for more details from response received from u/HaveAGitGat:
https://www.reddit.com/r/Tdarr/comments/l99nwt/v20003_release_31st_january_2021/glr9md2?utm_source=share&utm_medium=web2x&context=3

**Comment by karan** [comment]
@dambler if you can take a look

**Comment by HaveAGitGat** [comment]
It's to do with not entering any inputs. This should now be fixed.
