### ISSUE TITLE
Tdarr_Plugin_Img1_Reorder_Streams errors out

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#126]

**Comment by michpas** [comment]
I always run this plugin first on any videofile. Normally it works great.
Recently bumped into a few video files that error out on this step. (even if it's the only step active)

**Comment by supersnellehenk** [comment]
Dunno if this is still a problem, but your main problem is `[matroska @ 0x55fa0cfbc940] Subtitle codec 94213 is not supported.`. So you have a subtitle codec that won't fit in the file according to the MKV standards.

**Comment by michpas** [comment]
hi. thanks for the reply and helpful to know it's caused by an 'invalid subtitle codec'. Would there be a way for 'Tdarr_Plugin_Img1_Reorder_Streams' to identify and just continue instead of erroring out?
Reason for asking: this plugin the 1str plugin in a chain of file manipulations. If this one errors out, also the other modification script do not run.

**Comment by supersnellehenk** [comment]
Well, your file is invalid according to the MKV standards. So Reorder Streams isn't the plugin you're looking for, as that's designed for files that are conform their spec. You'd need something like `Tdarr_Plugin_MC93_Migz1Remux` with `force_conform` set to `true`. That'll remove those `mov_text` streams.

If you want to keep those `mov_text` streams, then I'd advise you to rename the file from `.mkv` to `.mp4`, as that's what it actually is.
