### ISSUE TITLE
Request: Move other specified files to output folder.

### ISSUE THREAD

**Issue by akanealw** [HaveAGitGat/Tdarr_Plugins#127]
My setup has Tdarr process my downloads folder and then copy them to a converted folder set as output to be grabbed by Sonarr/Radarr. It would be really nice if there was an option to specify other files to be copied as well, i.e. .nfo or .srt files. They wouldn't need to be processed, just copied.

Thanks!

**Comment by atmos-o** [comment]
I need this very thing as well. Is there no way with tdarr?

**Comment by HaveAGitGat** [comment]
Added flow plugin `Copy/Move Folder Content`

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/d5062fad-dc1d-4301-acc8-d8dfff7c07ac)
