### ISSUE TITLE
Bug: Tdarr_Plugin_henk_Add_Specific_Audio_Codec - doesn't work with files which have 2 or more streams to be converted 

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#129]
This plugin works great, where the input codec only occurs ones in the source file.

It doesn't work well if the input codec occurs more than 1 time. Than correct transcoding doesn't take place.

Example: one file with both DTS-XLL and DTS
Source parameters for plugin: dts
output parameters for plugin: aec3
	
preset that is being used:
` , -c copy -map 0:v -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 eac3 -b:a:1 640k -metadata:s:a:1 title="" -metadata:s:a:1 copyright="henk_asac" -map 0:a:1? -c:a:1 copy -map 0:a:1? -c:a:2 eac3 -b:a:2 640k -metadata:s:a:2 title="" -metadata:s:a:2 copyright="henk_asac" `

Outcome file : 
First audio: DTS-XLL (no henk copyright flag text)
Second Audio: DTS-XLL ? (with henk copyright flag text)  (This codec one was DTS) 
Third Audio: EAC3 (with henk copyright flag text)

Expected End result: 
4 audiotracks: One file with the same untouched 2 original DTS channels and 2 new ACS channels.

In addition, the end result is also without any embedded subtitles.  Could it be that these need to be added to be copied over?

Investigation:
In this situation the present should be a1 to a3 and a2 to a4. and incorrectly it tried to apply a1 to existing a2, giving unexpected outcome.

Hope you can find the time to look at this. It would make this plugin the perfect plugin for folks serving media files to multiple playback devices without worrying if the DTS or AC is included and keeping the original audiotracks intact

**Comment by supersnellehenk** [comment]
This is one of the earlier plugins I created, so yes it's a bit wonky. I'll try to fix these issues this week, if I have time.

> In addition, the end result is also without any embedded subtitles.

This is true, it only maps video and audio. I'll add this too, just an oversight when testing.

**Comment by michpas** [comment]
Thanks. Really appreciate it. Can you also add the  comment: ` -disposition:a:? 0 ` on every newly added audiostream? This will set their default flag to false; keeping the original default flag assigned.

**Comment by supersnellehenk** [comment]
> Thanks. Really appreciate it. Can you also add the comment: `-disposition:a:? 0` on every newly added audiostream? This will set their default flag to false; keeping the original default flag assigned.

I think it would be better to do `-disposition:a:? default`, that should just reset the default to false and leave everything else intact. Things like SDH and stuff.

**Comment by michpas** [comment]
Hi SuperSnelleHenk :-) Thanks that is great news.

Outside of the -disposition Were you also able to give a stab at the other two changes? 
1. The copying over of all subtitles from source to target
2. The correct adding of the new audiostream in case there are 2 or more original streams.

If so, I'm very keen to test.

**Comment by supersnellehenk** [comment]
> 1. The copying over of all subtitles from source to target
> 2. The correct adding of the new audiostream in case there are 2 or more original streams.

Yes, I did manage to fix these two things too. They're in pull request #131.

> If so, I'm very keen to test.

You could manually copy it from the mentioned PR, but I tested it a bit myself and I'm confident it works now ;).

**Comment by michpas** [comment]
Hi. Thanks for the quick resolution. I tested the plugin.

It functions great. 
    If there are 2 DTS streams it generated 2 EAC-3 streams.
    disposition also works 
    right EAC3 channels are tagged with 'henk_asac'
    Subs are kept.

One last bug found.
If the file has no subtitles, the plugin will error and puts the file in the error queu.
`Stream map '0:s' matches no streams. To ignore this, add a trailing '?' to the map.`

Thanks in advance for your effort

**Comment by supersnellehenk** [comment]
> `Stream map '0:s' matches no streams. To ignore this, add a trailing '?' to the map.`
Just pushed another commit adding that trailing `?` at the end. Should work fine now!

**Comment by michpas** [comment]
Thanks. Tested the new version. Subs works also good now.

One more interesting case with an error on this plugin, if I may
File has:
1. One Video stream AVC
2. One audio stream : MLP FBA, Meridian Lossless Packing FBA, Dolby TrueHD
no images or subs in the file.

ffmpeg -i '[file] .mkv' -c copy -map 0:v -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 eac3 -b:a:1 640k -metadata:s:a:1 title="" -metadata:s:a:1 copyright="henk_asac" -disposition:a:1 0 -map 0:s? '/tdarrcache/[file]-TdarrCacheFile-x7sRLSDv_.mkv'

This gives the error: 

`[eac3 @ 0x559af3736400] invalid sample rate
Error initializing output stream 0:2 -- Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height`

In the plugin conversation parameters I have: Input dts,trueHD    and output EAC3

Not sure, but it seems to be something to do wth the trueHD as audio stream as the plugin works great with DTS.

**Comment by supersnellehenk** [comment]
Could you provide a pastebin with all the info of that particular file? It's probably something to with sample rate being too high for EAC3, like it suggests.

**Comment by michpas** [comment]
> Could you provide a pastebin with all the info of that particular file? It's probably something to with sample rate being too high for EAC3, like it suggests.

Thanks for your offer to look into this case. Here is the file info: https://pastebin.com/q0S1j9Yw
I don't understand how the sample rate for EAC3 can be too high, as in the plugin it transcodes it from TrueHD to EAC3 640k; 
using the ffmpeg statement: ffmpeg -i '[file] .mkv' -c copy -map 0:v -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 eac3 -b:a:1 640k -metadata:s:a:1 title="" -metadata:s:a:1 copyright="henk_asac" -disposition:a:1 0 -map 0:s? '/tdarrcache/[file]-TdarrCacheFile-x7sRLSDv_.mkv'

**Comment by supersnellehenk** [comment]
> > Could you provide a pastebin with all the info of that particular file? It's probably something to with sample rate being too high for EAC3, like it suggests.
> 
> Thanks for your offer to look into this case. Here is the file info: [pastebin.com/q0S1j9Yw](https://pastebin.com/q0S1j9Yw)
> `I don't understand how the sample rate for EAC3 can be too high, as in the plugin it transcodes it from TrueHD to EAC3 640k; using the ffmpeg statement: ffmpeg -i '[file] .mkv' -c copy -map 0:v -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 eac3 -b:a:1 640k -metadata:s:a:1 title="" -metadata:s:a:1 copyright="henk_asac" -disposition:a:1 0 -map 0:s? '/tdarrcache/[file]-TdarrCacheFile-x7sRLSDv_.mkv'`

Yeah. The sample rate of that TrueHD is 96 kHz, but EAC3 only supports up to 48 kHz. That's the issue, so ffmpeg reports the correct thing. The 640k parameter is simply the bitrate, not the sample rate.

**Comment by michpas** [comment]
ah. Thanks. I learned something new today:-)

Would it be possible to also set the max sample rate in the ffmpeg command line, in case original is too high.? Similar to the bitrate of 640k? Google shows something like -ar 48000  or -af aresample=48000. 

Would this work to transcode the trueHD to an EAC3 stream?
Thanks
MIchel

**Comment by supersnellehenk** [comment]
> Would it be possible to also set the max sample rate in the ffmpeg command line, in case original is too high.? Similar to the bitrate of 640k? Google shows something like -ar 48000 or -af aresample=48000.

Yeah that could be done, but I'd have to look into it. Afaik it also kind of screws up the volume levels.

**Comment by michpas** [comment]
> > `Stream map '0:s' matches no streams. To ignore this, add a trailing '?' to the map.`
> 
> Just pushed another commit adding that trailing `?` at the end. Should work fine now!

Hi Supersnellehenk

Today I upgraded from Tdarr V1 to V2.
Your script Tdarr_Plugin_henk_Add_Specific_Audio_Codec on all my media files; as some new televisons don't accept DTS (new LG Oled series). Therefor I was glad to make use of your codec to add an extra audio channel if a DTS channel was found.
This script worked great on V1; but since I'm using V2, something goes wrong. The file seems to be in an endless loop and the script keeps on adding new audio channels. It seems it doesn't recognize the fact that the file has already been processed.

I tried to find the bug, but can't find anything wrong. Maybe something in V2 changed that stopped the logic of the 'copyright' tag. I would be very grateful if you can maybe spare a free moment to look at this
Thank you
Michel
