### ISSUE TITLE
Community Plugin: Tdarr_Plugin_henk_Add_Specific_Audio_Codec errors out

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#133]
I'm using the recently updated 'Tdarr_Plugin_henk_Add_Specific_Audio_Codec' a lot to ensure all videostreams with dts audio have also at least an EAC3 channel, as not all my players correctly support dts.

I'm now receiving errors some on the plugin on multiple files. The error states:
`Tdarr_Plugin_henk_Add_Specific_Audio_Codec - Pre-processing ☒Plugin error! TypeError: Cannot read property 'COPYRIGHT' of undefined`

Just a mkv file with 1 video stream and 1 audio stream with aac. In the parameters of plugin I entered 'dts' as source. To be honest I don't know why the plugin script would even pick this up as it's not dts
The file information can be found here: https://pastebin.com/JYBvJFUS

Thanks for your time.

**Comment by michpas** [comment]
I have found the fix.


--existing code that errors out
  for (let i = 0; i < file.ffProbeData.streams.length; i += 1) {
    const currStream = file.ffProbeData.streams[i];
    if (currStream.tags.COPYRIGHT) {
      if (currStream.tags.COPYRIGHT === 'henk_asac') {
        killPlugin = true;
      }
    }
  }
--new code that is ok
 for (let i = 0; i < file.ffProbeData.streams.length; i += 1) {
    const currStream = file.ffProbeData.streams[i];
    if (currStream.codec_type.toLowerCase() === 'audio' && currStream.tags.copyright) {
      if (currStream.tags.copyright === 'henk_asac') {
        killPlugin = true;
      }
    }
  }

**Comment by HaveAGitGat** [comment]
This should be fine now. Reopen if needed, thanks.
