### ISSUE TITLE
read error for plugin Tiered FFMPEG+NVENC CQ:V BASED CONFIGURABLE

### ISSUE THREAD

**Issue by repomanz** [HaveAGitGat/Tdarr_Plugins#134]
I'm trying to use the 'Tiered FFMPEG+NVENC CQ:V BASED CONFIGURABLE' plugin for transcoding a library. When adding however I get a read error after i've added it to the transcoding options

![image](https://user-images.githubusercontent.com/20090451/109549770-073b3000-7a94-11eb-9f2d-441d818e8110.png)

**Comment by HaveAGitGat** [comment]
Make sure the plugin ID is the same as the file name. I think that might have been the issue. Reopen if needed, thanks.
