### ISSUE TITLE
bug: Bug: Tdarr_Plugin_henk_Add_Specific_Audio_Codec - Since upgraded from Tdarr v1 to Tdarr v2 the script loops

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#152]
Hi Supersnellehenk

Today I upgraded from Tdarr V1 to V2.
Your script Tdarr_Plugin_henk_Add_Specific_Audio_Codec runs on all my media files; as some new televisons don't accept DTS (new LG Oled series). There for I was glad to make use of your script to add an extra audio channel if a DTS channel was found.
This script worked great on V1; but since I'm using V2, something goes wrong. The file seems to be in an endless loop and the script keeps on adding new audio channels. It seems it doesn't recognize the fact that the file has already been processed.

I tried to find the bug, but can't find anything wrong. Maybe something in V2 changed that stopped the logic of the 'copyright' tag. I would be very grateful if you can maybe spare a free moment to look at this
Thank you
Michel

**Comment by supersnellehenk** [comment]
I get the same looping behaviour. I'll give it a proper look sometime. Should probably clean up the code too...

**Comment by michpas** [comment]
I did some more testing.
The issue is with " 

The correct testing part is:

  if (currStream.codec_type.toLowerCase() === 'audio'  && currStream.codec_name === inputs.output_codec  ) {
    if (currStream.tags.COPYRIGHT === 'henk_asac') {
        killPlugin = true;


The correct end part is: (without the "on "'henk_asac"
      response.preset += ` -map 0:a:${indexCount}? -c:a:${streamCount} ${inputs.output_codec || 'ac3'} ${bitrate} `
          + `-metadata:s:a:${streamCount} title=" " -metadata:s:a:${streamCount} copyright=henk_asac `
          + `-disposition:a:${streamCount} 0`;
        streamCount += 1;

With this, it should work again. 
Great if you can make these updates in teh community version
Thanks

**Comment by michpas** [comment]
I also noticed another thing. Plex always plays the first audiostream (in the chosen language)'; it doesn't look for 'default' tags; not is plex smart enough that if in the plex setting a person states 'no dts compatible'; plex will still play the dts stream if it'first. even if there is an eac3 stream available; resulting in transcoding.
Have tried many variances and options; but only thing that seems to work is to make the eac3 stream come prior to the dts.

In your plugin, would it be possible to have a paramter that states: 'new audio stream before or after the original stream'? So people can choose?
Thanks

**Comment by michpas** [comment]
The last item on this plugin. It seems that if there is already an audio stream in the desired codec, but without the existance of the copyright tag, the script errors out with:  ☒Plugin error! TypeError: Cannot read property 'COPYRIGHT' of undefined
If there is some way to test the existance of the copyright tag before trying to read it, that would avoid this error

**Comment by michpas** [comment]
Solved
