### ISSUE TITLE
Tdarr_Plugin_z18s_rename_files_based_on_codec.js & Tdarr_Plugin_z18t_rename_files_based_on_codec_and_resolution.js N/F

### ISSUE THREAD

**Issue by joelang1699** [HaveAGitGat/Tdarr_Plugins#158]
Both plugins will not add the codec info i.e. x264 to x265 or add the resolution in V2.

V1 still works with no issues.

**Comment by davidrobertson** [comment]
I can also confirm that neither plugin is renaming files.  Try as I might, I have not been able to make either one work.

**Comment by joelang1699** [comment]
I've went back to v1 for the time being as without the rename function it just creates loads of manual work.

**Comment by davidrobertson** [comment]
From what I can tell, including external modules (like fs-extra) on v2 is failing for _some_ users, but not all.  Unfortunately I am one of those users.

My solution was to write a new plugin that calls an external shellscript via 'exec' to handle the renaming.  It's stupid and I hate it, but it works perfectly 🤷‍♂️

**Comment by eknoop** [comment]
> From what I can tell, including external modules (like fs-extra) on v2 is failing for _some_ users, but not all. Unfortunately I am one of those users.
> 
> My solution was to write a new plugin that calls an external shellscript via 'exec' to handle the renaming. It's stupid and I hate it, but it works perfectly 🤷‍♂️

Care to share?

I wonder if the fs-extra issue has to do with running in docker...are you running in docker as well?

**Comment by pellz0r** [comment]
This looks to be solved by the update HaveAGitGat did to the plugins yesterday. It works for me now at least :D

**Comment by HaveAGitGat** [comment]
Yeah this was to do with fs-extra, I removed it so should be working fine. Re-open if needed, thanks.
