### ISSUE TITLE
Tdarr_Plugin_MC93_Migz2CleanTitle not fully compatible with Tdarr v2?

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr_Plugins#160]
I frequently run into this error:
```
Migz-Clean title metadata - Pre-processing
☒Plugin error! TypeError: Cannot read property 'toLowerCase' of undefined 
```
I'm told this is probably because the plugin is not completely compatible with Tdarr v2 yet. It would be nice if it where updated.

**Comment by HaveAGitGat** [comment]
The new loadDefaultValues function should fix this. Should now be working.
