### ISSUE TITLE
Tdarr_Plugin_e5c3_CnT_Keep_Preferred_Audio not fully compatible with Tdarr v2?

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr_Plugins#161]
I frequently run into this error:
```
Keep Preffered Audio - Pre-processing
☒Plugin error! TypeError: Cannot read property 'substring' of undefined 
```
I'm told this is probably because the plugin is not completely compatible with Tdarr v2 yet. It would be nice if it where updated.

**Comment by HaveAGitGat** [comment]
The new loadDefaultValues function prevents this error.
