### ISSUE TITLE
Extra quotes when adding metadata

### ISSUE THREAD

**Issue by gauth-fr** [HaveAGitGat/Tdarr_Plugins#163]
Im using the latest versions of tdarr/node.

In a plugin im making, im' trying to add some title to audio like "fre AAC 5.1".

Im doing something like that:
          title="5.1 "+inputs.tag_language
          ffmpegCommandInsert += \`-metadata:s:a:${audioIdx} title='${title}' \`;
It's working, but in the end, when i check the metadata i have:
"tags": {
          "language": "fre",
          "title": "'fre AAC 5.1'",     <---- note that the single quotes are in the metadata

I tried ffmpegCommandInsert += \`-metadata:s:a:${audioIdx} title='${title}' \`; (with doucle quotes)
I end up with "title": "\"fre AAC 5.1\"" in the metadata

I tried without double/quotes : it won't works because AAC and 5.1 and not valid input parameter
But it works if the title is a single word.

Note that i tried through the CLI and and it works fine (no double/quotes added to the metadata.

So i guess there are some double/quotes escaping done some where when executing the ffmpeg command?

Any way to fix that?

Thanks!

PS: sorry i don't know how to remove the "red a".. which should be : a :

**Comment by HaveAGitGat** [comment]
Answered here:

https://github.com/HaveAGitGat/Tdarr/issues/465
