### ISSUE TITLE
Titles on MP4 streams not "scanned" by tdarr

### ISSUE THREAD

**Issue by gauth-fr** [HaveAGitGat/Tdarr_Plugins#164]
Im trying to set audio title on some mp4 files.
I'm trying using Tdarr_Plugin_MC93_Migz3CleanAudio.
It will be stop to prevent infite loop (well done :) very good idea :) ) with the following:
```
The new transcode arguments were the exact same as the last ones meaning
the file/worker would most likely be stuck in an infinite transcode loop if not stopped.
Last arguments: , -map 0 -metadata:s:a:0 title="5.1" -c copy -max_muxing_queue_size 9999
New arguments: , -map 0 -metadata:s:a:0 title="5.1" -c copy -max_muxing_queue_size 9999
Plugin Community Tdarr_Plugin_MC93_Migz3CleanAudio
```

Actually i tried manually with ffmpeg and it works. However if you check the output file with ffmpeg/ffprobe, you won't see the title (for a reason i don't explain)
But i tried with mediainfo, i can see the title on the ouput file:
```
Stream size                              : 2.82 MiB (29%)
Title                                    : 5.1
Language                                 : French

```
By the way, it's shown for example in VLC
Are the metadata not updated between each run of a plugin?

Anyway, it seems "unmanaged" by tdarr, because if i put the mp4 with title in my scanned folder, i cannot see the title in the file metadata in tdarr.

Any idea how to solve the issue?

**Comment by HaveAGitGat** [comment]
FFprobe was recently updated, also worth checking the 'meta' info in the file object. The metadata should be updated between each run of a plugin.

Please reopen if you still have the issue on 2.00.12 (latest), thanks.
