### ISSUE TITLE
Tdarr_Plugin_Mthr_VaapiHEVCTranscode Shows error of "Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by gofireworks** [HaveAGitGat/Tdarr_Plugins#169]
Hello, I am trying to use the Tdarr_Plugin_Mthr_VaapiHEVCTranscode plugin, but I am getting an error that says the following:

`Pre-processing - FFMPEG VAAPI HEVC Transcode☒Plugin error! TypeError: Cannot read property 'toLowerCase' of undefined`

I am not sure why this is happening, as other plugins are working properly. Does anyone happen to know why this may be? Thanks for any help!

**Comment by PwnPeter** [comment]
> Hello, I am trying to use the Tdarr_Plugin_Mthr_VaapiHEVCTranscode plugin, but I am getting an error that says the following:
> 
> `Pre-processing - FFMPEG VAAPI HEVC Transcode☒Plugin error! TypeError: Cannot read property 'toLowerCase' of undefined`
> 
> I am not sure why this is happening, as other plugins are working properly. Does anyone happen to know why this may be? Thanks for any help!

Just add "false" in "remuxOnly", default value does not seem to work :)
![image](https://user-images.githubusercontent.com/36985538/132928515-1eb38f75-5d0d-4a1d-8a01-f917afed5b56.png)

**Comment by HaveAGitGat** [comment]
The new loadDefaultValues function prevents this error.
