### ISSUE TITLE
Tdarr_Plugin_MC93_Migz6OrderStreams does not check if the first audio stream is 2.0

### ISSUE THREAD

**Issue by Cycor** [HaveAGitGat/Tdarr_Plugins#170]
There is a compare on line 62 that will always return false causing the 2.0 channel track not to be recognized:

// Check if audio track is 2 channel.
if (file.ffProbeData.streams[i].channels === '2')

changing it to this works:
if (file.ffProbeData.streams[i].channels === 2)

**Comment by HaveAGitGat** [comment]
Thanks, fixed here: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/212
