### ISSUE TITLE
Tdarr_Plugin_a9hd_FFMPEG_Transcode_Specific_Audio_Stream_Codecs: Error when bitrate unspecified

### ISSUE THREAD

**Issue by karan** [HaveAGitGat/Tdarr_Plugins#172]
New to tdarr and trying to convert my RIPs with `aac` audio to `ac3` audio while preserving channel count and bitrate.

I'm using only this plugin in my stack, with bitrate unset.

Command:

```
Command:

ffmpeg -i /mnt/media/One Winter Weekend (2018)/One.Winter.Weekend.2018.HDTV-720p.x264.AAC.mp4 -c copy -map 0:v -map 0:1 -c:1 ac3 -b:a -map 0:s? -map 0:d? -max_muxing_queue_size 9999 /temp/One.Winter.Weekend.2018.HDTV-720p.x264.AAC-TdarrCacheFile-zq908QTvU.mp4
```

Error:

```
[NULL @ 0x55fb40110cc0] Unable to find a suitable output format for '0:s?'

0:s?: Invalid argument

Tdarr ALERT: NO OUTPUT FILE PRODUCED:
```

I would expect `-b:a` to not be set based on https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_a9hd_FFMPEG_Transcode_Specific_Audio_Stream_Codecs.js#L95.

That's what seems to be the issue here.

**Comment by supersnellehenk** [comment]
If you've never filled an input field, it returns undefined in Tdarr. However, as is the case here, when it has been filled, but emptied, it returns an empty string. So the check is wrong on that line.

**Comment by HaveAGitGat** [comment]
The new loadDefaultValues function should fix this.
