### ISSUE TITLE
Tdarr_Plugin_MC93_Migz1FFMPEG_CPU  Migz-Transcode Using CPU & FFMPEG

### ISSUE THREAD

**Issue by bullmoose20** [HaveAGitGat/Tdarr_Plugins#177]
Some of my videos are failing conversion with the following error: 
x265 [error]: Picture width must be an integer multiple of the specified chroma subsampling
This solution below seems like a pretty good workaround. Can it be implemented in your plugin?

https://stackoverflow.com/questions/20847674/ffmpeg-libx264-height-not-divisible-by-2/20848224#20848224

Details of error:
Command: 
ffmpeg -i /mnt/media/Movies/Thor Ragnarok (2017)/Thor Ragnarok 2017 WEBDL-1080p.mkv -map 0 -c:v libx265 -b:v 2692k -minrate 1884k -maxrate 3499k -bufsize 5385k -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -v:0 -map -v:1 -map -v:2 -map -v:3 /temp/Thor Ragnarok 2017 WEBDL-1080p-TdarrCacheFile-L80HcV2YH.mkv
Last 200 lines of CLI log:
 ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --nvccflags='-gencode arch=compute_52,code=sm_52 -O2' --disable-debug --disable-doc --disable-ffplay --disable-static --enable-cuda-nvcc --enable-cuda-sdk --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-openssl --enable-shared --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100

  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

[h264 @ 0x5631e88a4ec0] SEI type 5 size 6160 truncated at 200

[h264 @ 0x5631e88a4ec0] SEI type 5 size 6160 truncated at 192

Input #0, matroska,webm, from '/mnt/media/Movies/Thor Ragnarok (2017)/Thor Ragnarok 2017 WEBDL-1080p.mkv':

  Metadata:
    title           : Thor.Ragnarok.2017.1080p.WEB-DL.DD5.1.H264-FGT

    encoder         : 
libebml v1.3.5 + libmatroska v1.4.8

    creation_time   : 2018-01-21T09:05:54.000000Z
  Duration: 02:10:44.09
, start: 0.000000, bitrate: 5646 kb/s
    Chapter #0:0: start 0.000000, end 380.000000
    Metadata:
      title           : The Great Prophecy
    Chapter #0:1: start 380.000000, end 851.000000
    Metadata:
      title           : The Tragedy Of Loki Of Asgard
    Chapter #0:2: start 851.000000, end 1332.000000
    Metadata:
      title           : A Worthy Inclusion
    Chapter #0:3: start 1332.000000, end 1599.000000
    Metadata:
      title           : 
The Goddess Of Death
    Chapter #0:4: start 1599.000000, end 1889.000000
    Metadata:
      title           : \"Are You A Fighter, Or Are You Food?\"
    Chapter #0:5: start 1889.000000, end 2103.000000
    Metadata:
      title           : Heiress Apparent
    Chapter #0:6: start 2103.000000, end 2569.000000
    Metadata:
      title           : The Grandmaster
    Chapter #0:7: start 2569.000000, end 2910.000000
    Metadata:
      title           : The Eternal Flame
    Chapter #0:8: start 2910.000000, end 3578.000000
    Metadata:
      title           : The Contest Of Champions
    Chapter #0:9: start 3578.000000, 
end 4078.000000
    Metadata:
      title           : The Resistance
    Chapter #0:10: start 4078.000000, end 4650.000000
    Metadata:
      title           : Hotheaded Fools
    Chapter #0:11: start 4650.000000, end 5245.000000
    Metadata:
      title           : The Revengers
    Chapter #0:12: start 5245.000000, end 5768.000000
    Metadata:
      title           : \"The Revolution Has Begun\"
    Chapter #0:13: start 5768.000000, end 6155.000000
    Metadata:
      title           : Ready For War
    Chapter #0:14: start 6155.000000, end 6560.000000
    Metadata:
      title           : \"Asgard Is Not A Place\"
    Chapter #0:15: 
start 6560.000000, end 6897.000000
    Metadata:
      title           : \"What Were You The God Of Again?\"
    Chapter #0:16: start 6897.000000, end 7237.000000
    Metadata:
      title           : Ragnarok
    Chapter #0:17: start 7237.000000, end 7844.086000
    Metadata:
      title           : End Credits

    Stream #0:0: Video: h264, yuv420p(tv, bt709, progressive), 1920x800, SAR 1:1 DAR 12:5, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : Thor.Ragnarok.2017.1080p.WEB-DL.DD5.1.H264-FGT
      BPS             : 5260592
      BPS-eng         : 5260592
      DURATION        : 02:10:44.086000000
      DURATION-eng    : 02:10:44.086000000
      NUMBER_OF_FRAMES: 188070

      NUMBER_OF_FRAMES-eng: 188070
      NUMBER_OF_BYTES : 5158067284
      NUMBER_OF_BYTES-eng: 5158067284
      _STATISTICS_WRITING_APP: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-01-21 09:05:54
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-01-21 09:05:54
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      title           : Thor.Ragnarok.2017.1080p.WEB-DL.DD5.1.H264-FGT
      BPS             : 384000
      BPS-eng         : 384000

      DURATION        : 02:10:44.064000000
      DURATION-eng    : 02:10:44.064000000
      NUMBER_OF_FRAMES: 245127
      NUMBER_OF_FRAMES-eng: 245127
      NUMBER_OF_BYTES : 376515072
      NUMBER_OF_BYTES-eng: 376515072
      _STATISTICS_WRITING_APP: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-01-21 09:05:54
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-01-21 09:05:54
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip (default)
    Metadata:
      BPS             :49
      BPS-eng         : 49
      DURATION        : 02:09:19.421000000
      DURATION-eng    : 02:09:19.421000000
      NUMBER_OF_FRAMES: 1568
      NUMBER_OF_FRAMES-eng: 1568
      NUMBER_OF_BYTES : 48231
      NUMBER_OF_BYTES-eng: 48231
      _STATISTICS_WRITING_APP: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-01-21 09:05:54
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-01-21 09:05:54
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

    Stream #0:3: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 120x176, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      filename        : small_cover.jpg
      mimetype        : image/jpeg
    Stream #0:4: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 213x120, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      filename        : small_cover_land.jpg
      mimetype        : image/jpeg

    Stream #0:5: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 600x882, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      filename        : cover.jpg
      mimetype        : image/jpeg
    Stream #0:6: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1067x600, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      filename        : cover_land.jpg

      mimetype        : image/jpeg

Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
  Stream #0:6 -> #0:2 (mjpeg (native) -> hevc (libx265))
Press [q] to stop, [?] for help

x265 [info]: HEVC encoder version 3.2.1+1-b5c86a64bbbe

x265 [info]: build info [Linux][GCC 9.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
**x265 [error]: Picture width must be an integer multiple of the specified chroma subsampling
[libx265 @ 0x5631e89b3f80] Cannot open libx265 encoder.
Error initializing output stream 0:2 -- Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height

Conversion failed!**

**Comment by supersnellehenk** [comment]
You need to use this plugin https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_MigzImageRemoval.js your issue is the mjpeg trying to be converted which won't work.

**Comment by bullmoose20** [comment]
OK. I will try that plugin... but curious. Would it not be nice to have the healthcheck fail, and then offer that plugin as a solution? Just thinking that the healthcheck should have caught this?

**Comment by supersnellehenk** [comment]
> OK. I will try that plugin... but curious. Would it not be nice to have the healthcheck fail, and then offer that plugin as a solution? Just thinking that the healthcheck should have caught this?

Health checks serve a completely different purpose. A quick health check checks if the file headers are fine. A thorough check checks each frame for corruption.

**Comment by bullmoose20** [comment]
Last question(I hope)... I presume I add this plugin just after the first one and before the actual transcode plugin so that it "cleans" before it transcodes?

**Comment by supersnellehenk** [comment]
> Last question(I hope)... I presume I add this plugin just after the first one and before the actual transcode plugin so that it "cleans" before it transcodes?

I personally run `Tdarr_Plugin_vdka_Remove_DataStreams`, then `Tdarr_Plugin_lmg1_Reorder_Streams`, then `Tdarr_Plugin_MC93_MigzImageRemoval`. After that follow all other (transcode) plugins.

**Comment by bullmoose20** [comment]
Thanks so much for your help and for your guidance on the plugins you use. I will try it all and see how things go. Have a great day!
