### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr_Plugins#18]
Can someone create a plugin that only transcodes non-hevc files into hevc files keeping everything in the output the same. For example, same output container as the input, same audio tracks, same subtitles, everything. Just transcoding to hevc for space savings.

**Comment by HaveAGitGat** [comment]
The first community plugin will do this  except the container is mkv.

Tdarr_Plugin_075a_FFMPEG_HEVC_Generic

**Comment by clifford64** [comment]
Right, but MKV doesn't always support the items that may be included within an mp4 or m4v. If I can just transcode the video, I don't have to worry about converting all the extra stuff to make sure it is compatible with mkv.

**Comment by clifford64** [comment]
I am currently using the below which copys all audio streams, converts video to x265 mkv, converts all subtitle streams to SRT, removes metadata.
response.preset = `,-map 0 -c copy -c:v libx265 -c:s srt -dn -map_metadata -1 -map_chapters -1`

**Comment by HaveAGitGat** [comment]
@clifford64 great.

Another way would be to copy the Tdarr_Plugin_075a_FFMPEG_HEVC_Generic plugin into your local plugins folder and change the container from mkv to` '.' +file.container` so it keeps the original (and also add the other changes you've made).

**Comment by clifford64** [comment]
That could also work. I have a week off for Christmas, so I am probably going to dive deeper into this and see if I can make a script to copy subtitle if it is pgs or other subtitle that works in mkv, but cannot be converted to srt, else convert to srt, else drop subtitle and transcode video. I don't have great knowledge of Linux scripting and functions, but I might be able to reverse engineer something.

Do you know what command is used to probe files to get the pre-process info used in the filters and such?

**Comment by HaveAGitGat** [comment]
Yeah look at some of the community plugins to get an idea of how things work. And all file data can be viewed if you search for a file and press the 'i' button.

Unfortunately I'm just beginning a 2 week break from the keyboard to rest an injury but someone in the discord room might be able to help if you get stuck.

**Comment by HaveAGitGat** [comment]
Please re-open if you still need help
