### ISSUE TITLE
Tdarr_Plugin_43az_add_to_radarr

### ISSUE THREAD

**Issue by PierreDurrr** [HaveAGitGat/Tdarr_Plugins#185]
Is this plugin working with Radarr v3 ?
I've just imported it from Plugins tab and added to my stack as only plugin. No other transcode option enabled. But it seems that this doesn't work.
Processing is ok but nothing is added to my radarr...
Am i missing something ?

**Comment by HaveAGitGat** [comment]
This shouldn't be needed these days as Radarr should pickup the file. You can use this plugin after transcoding to notify radarr/sonarr of new file:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/4aad2901-7414-4380-9cde-923dcf5ce904)

**Comment by yodog** [comment]
@HaveAGitGat 

for some reason when replaceOriginalFile does *not* replace the file, NotifyRadarrOrSonarr causes a flow error

TypeError: Cannot read properties of undefined (reading 'movieFile')
