### ISSUE TITLE
[Plugin Request] cloudbox/autoscan support

### ISSUE THREAD

**Issue by deathbybandaid** [HaveAGitGat/Tdarr_Plugins#191]
Cross-linking this here, from there.

https://github.com/Cloudbox/autoscan/issues/134#issue-1013390810

the old plex_autoscan requires cli access to the plex application whereas cloubox/autoscan  uses plex's API, which feels like less of a security issue and breaking point.

I assume the existing autoscan plugin could be cloned and tweaked to do the different POST request.
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_MigzPlex_Autoscan.js

**Comment by mikertoad** [comment]
Did this recently and you can find the pull request here - https://github.com/HaveAGitGat/Tdarr_Plugins/pull/192

Hopefully this does what you're looking for

**Comment by goofballtech** [comment]
#217 uses plex's API directly, may also be a way to serve your purpose, i didn't want to have to spin up another app or docker for a simple refresh.

**Comment by deathbybandaid** [comment]
one of the benefits of cloudbox/autoscan is that you don't have to map library IDs, and you can send the request to multiple simultaneous servers, as well as emby/jellyfin along with Plex.
