### ISSUE TITLE
Unrecognized option 'rc:v'

### ISSUE THREAD

**Issue by wgstarks** [HaveAGitGat/Tdarr_Plugins#200]
I'm trying to get a node running on an old MacPro with an Nvidia geforce 8800 graphics card but every file keeps failing-

`NodeID: maggie 
Command: 
/Applications/TDARR/Tdarr_Node/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg -c:v h264_cuvid -i /Volumes/Media/XBMC/Torrents/The Pink Panther Strikes Again (1976)/The Pink Panther Strikes Again (1976).Bluray-1080p.x264 DTS-AMIABLE.mkv -map 0 -c:v hevc_nvenc -rc:v vbr_hq -cq:v 19 -b:v 7216k -minrate 5051k -maxrate 9380k -bufsize 14432k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -pix_fmt p010le -bf 5 /Volumes/Media/tdarr_transcode/The Pink Panther Strikes Again (1976).Bluray-1080p.x264 DTS-AMIABLE-TdarrCacheFile-QfCBKdKu2.mkv
Last 200 lines of CLI log:
ffmpeg version N-92718-g092cb17983-tessus https://evermeet.cx/ffmpeg/ Copyright (c) 2000-2018 the FFmpeg developers
built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil 56. 24.101 / 56. 24.101
libavcodec 58. 42.102 / 58. 42.102
libavformat 58. 24.101 / 58. 24.101
libavdevice 58. 6.101 / 58. 6.101
libavfilter 7. 46.101 / 7. 46.101
libswscale 5. 4.100 / 5. 4.100
libswresample 3. 4.100 / 3. 4.100
libpostproc 55. 4.100 / 55. 4.100
Unrecognized option 'rc:v'.
Error splitting the argument list: Option not found
Tdarr ALERT: NO OUTPUT FILE PRODUCED: 
/Volumes/Media/tdarr_transcode/The Pink Panther Strikes Again (1976).Bluray-1080p.x264 DTS-AMIABLE-TdarrCacheFile-QfCBKdKu2.mkv`

This is on a MacPro (early 2008) running High Sierra (macOS 10.13.6).
I'm hoping I can put this old machine to good use.😁

**Comment by supersnellehenk** [comment]
That card doesn't have an nvenc chip needed to encode, the first generation got added on the 600 series in 2012. https://en.m.wikipedia.org/wiki/Nvidia_NVENC

**Comment by wgstarks** [comment]
So won’t work?

**Comment by supersnellehenk** [comment]
Nope. The GPU is too old.

**Comment by wgstarks** [comment]
Looks like it's handling the non-NVENC stuff though. Clean up audio and subs for videos already x265. Might let it process all of them and then requeue the failed. Save a little time maybe???

**Comment by supersnellehenk** [comment]
Those are CPU tasks, not GPU. So yeah those can be done by that Mac.

**Comment by wgstarks** [comment]
Thanks. Closing this since it's not an issue with TDARR.
