### ISSUE TITLE
Plugin: Tdarr_Plugin_henk_Add_Specific_Audio_Codec Errors out

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#202]
This plugin: Tdarr_Plugin_henk_Add_Specific_Audio_Codec.js 
When going processing a file that already has the desired audiostream (in my case EAC3), but no 'copyright' label, the script  errors out.

The error is:
Tdarr_Plugin_henk_Add_Specific_Audio_Codec - Pre-processing
☒Plugin error! TypeError: Cannot read property 'COPYRIGHT' of undefined.

I think it errors as it tries to read a property, but the actual property doesn't exist.

Example of mediainfo: below.

ormat                                   : Matroska
Format version                           : Version 4
File size                                : 1.36 GiB
Duration                                 : 46 min 5 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 4 225 kb/s
Writing application                      : mkvmerge v30.1.0 ('Forever And More') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 46 min 5 s
Bit rate mode                            : Variable
Bit rate                                 : 3 650 kb/s
Maximum bit rate                         : 5 475 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.073
Stream size                              : 1.13 GiB (83%)
Writing library                          : x264 core 148 r2715 7e75228
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=2 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=24 / scenecut=0 / intra_refresh=0 / rc_lookahead=48 / rc=2pass / mbtree=1 / bitrate=3650 / ratetol=1.0 / qcomp=0.50 / qpmin=6 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=5475 / vbv_bufsize=7300 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 46 min 5 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 211 MiB (15%)
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

**Comment by supersnellehenk** [comment]
I created a PR to fix this. Might take a while to be approved.

**Comment by michpas** [comment]
Hi I created a local copy with these changes. Works great. Error is gone. 
Thanks
