### ISSUE TITLE
h264 aac mkv -> mp4

### ISSUE THREAD

**Issue by evoactivity** [HaveAGitGat/Tdarr_Plugins#205]
**Describe the bug**
I'm converting a collection from mkv to mp4 for easy web browser streaming. If the mkv is already h264 and aac it gets reported as not required and doesn't get remuxed.

It seems like the container is not considered when making the decision if a file needs processing or not. 

**To Reproduce**
Try to convert an h264 aac mkv to an mp4, Tdarr will report it is not required and leave the file as is. 

I've tried different presets for 
Tdarr_Plugin_z3ab_TheRealShadoh_FFmpeg_Subs_H264_{preset}
and
Tdarr_Plugin_da11_Dallas_FFmpeg_Presets_H264_MP4

all exhibit the same issue

**Expected behavior**
If no transcoding needs to happen it still should remux to the mp4 container

 - OS: Ubuntu
 - Browser Firefox
 - Version 2.00.11

**Comment by HaveAGitGat** [comment]
Quick fix for this is to add a remux mp4 plugin to your stack, not sure if those guys designed them that way:

![image](https://user-images.githubusercontent.com/43864057/145869277-ba69a909-0e2e-4956-8880-7d2e0989c203.png)
![image](https://user-images.githubusercontent.com/43864057/145869232-4cce5e08-3ff3-4ff6-a871-eb4b7f63d027.png)
