### ISSUE TITLE
Plugin processing cache files

### ISSUE THREAD

**Issue by ferferga** [HaveAGitGat/Tdarr_Plugins#216]
Hello

I've been debugging this for days but with the docs I have no clue what is causing this.

I have made my own local plugin. My pugin makes a request to scan the file, so mediaInfo is available for it, like this:
```
const httpRequest = await axios.post(
    'http://IP:8265/api/v2/scan-individual-file',
    {
      data: {
        headers: { 'content-Type': 'application/json' },
        file: {
          file: file.file,
          _id: file._id
        },
        scanTypes: {
          exifToolScan: false,
          mediaInfoScan: true,
          closedCaptionScan: false
        }
      }
    },
    { timeout: 0 }
  );

 const scannedFile = httpRequest.data;
```

When a file doesn't meet the criteria, I set ``processFile`` to ``false`` and the file is marked as "Not required" in the UI. When a file matches my criteria, I set it to ``true`` and it gets processed correctly and the progress appears in the UI. 

However, when the file completes, tdarr passes the transcoded file again through that plugin, which fails because the mediaInfo field I use later on my plugin it's not defined for that temporary file:

```
[2021-12-17T00:10:36.505] [INFO] Tdarr_Node - Processing file: /media/file.mkv
[2021-12-17T00:31:53.795] [INFO] Tdarr_Node - verbose:Sub-worker exit status received
[2021-12-17T00:31:54.247] [INFO] Tdarr_Node - verbose:Sub-worker exited
[2021-12-17T00:32:10.598] [INFO] Tdarr_Node - Processing file: /tmp/file-TdarrCacheFile-b9Ye5XCTl.mkv
[2021-12-17T00:32:10.623] [INFO] Tdarr_Node - verbose:Item request received
[2021-12-17T00:32:10.623] [INFO] Tdarr_Node - verbose:Getting new task
[2021-12-17T00:32:10.621] [WARN] Tdarr_Node -
Pre-processing - *PluginName* Plugin error! TypeError: scannedFile.mediaInfo.track is not iterable
```

How I can disable this behaviour? Why it's enabled by default? It makes no sense to me.

Thank you very much in advance.

**Tdarr version**: 2.00.12
**Platform**: Docker on armv7 (armhf)

**Comment by rick-meijer** [comment]
First things first, MediaInfo data should be available in the file object that gets passed to a plugin.

Besides that: Tdarr loops a file through all the plugins until each plugin marks said item as done, then moves on to the next. When it picks it up after transcoding is done to it, it starts at plugin 1 and works it's way down again. That's intended behaviour.

Could you explain what your plugin does? Not a lot of plugins need MediaInfo as ffprobe usually provides enough data.

**Comment by ferferga** [comment]
I expected it too but it isn't. I even rescanned my whole library, making sure that MediaInfo was ticked, and no luck. You can check this very easily: just click on any file and it will state "Scanning" at the top. Before it is completed, no MediaInfo key will appear.

I only have one plugin. The plugin compares bitrates, resolutions and codecs to determine whether if a file needs transcoding or not. There should be only one iteration (as I only have one plugin) but tdarr thinks that the new transcoded file also needs a pass to check if it meets the criteria, which in my opinion doesn't make sense (and that's why I want to disable it). 

ffprobe doesn't provide predictable info on the returned information and includes a lot of unneeded stuff for my use case, like header tags.

**Comment by supersnellehenk** [comment]
You can't change how Tdarr works regarding plugins, so that's a no go. Does mediaInfo show up as working in the node/server? Because on my unraid install it works, but that's x86_64, maybe there's a difference compared to ARM.

**Comment by HaveAGitGat** [comment]
```
  "mediaInfo": {
    "@ref": "",
    "track": [
      {
        "@type": "General",
        "UniqueID": "284442494714348265438954623544328950024",
        "VideoCount": "1",
        "AudioCount": "1",
        "Format": "Matroska",
        "Format_Version": "4",
        "FileSize": "1181843829",
```

I just clicked on a file with Tdarr running in Raspberry Pi v7 container and the info comes up fine.

You don’t need to rescan all your files, they are scanned when a worker processes them and the mediaInfo and all other data is passed to the plug-in.

As mentioned in the plugin guide on the plugins tab, the file passes through the plug-in stack after processing to check all conditions are met on the new file.

It’s not uncommon for FFmpeg and HandBrake to fail to process the file as desired (but still finish ‘successfully’)  so checking the output file is a necessary step.

**Comment by ferferga** [comment]
For me they appear only with the ffprobe first and after a few seconds, with mediaInfo (as UI calls the /scan-individual-item endpoint)

However, can you verify that MediaInfo its also available for files that are just transcoded (just need to be copied) under the temporary directory? That would solve the problem for me.

For reference, I'm not replacing library files, I have the output to another folder recreating the original folder structure.

**Comment by supersnellehenk** [comment]
> For me they appear only with the ffprobe first and after a few seconds, with mediaInfo (as UI calls the /scan-individual-item endpoint)

If you click the file in the UI, yeah that's how it works. However, Tdarr scans the file in between each time it does something to a file. Just console log the file object, it's there. No need to call the endpoint yourself.

**Comment by HaveAGitGat** [comment]
@ferferga yeah the mediaInfo is only collected when you click on a file (on-demand scan) or when the file is processed by a plugin. It used to be that all mediaInfo and exifTool info was collected and stored during the initial library scan but this resulted in huge database sizes when having hundreds of thousands of files.

I just added the following console.log to an example plugin on the Raspberry Pi:

```
const plugin = (file, librarySettings, inputs, otherArguments) => {
  console.log(file);
```

In the node log, when the item is picked up by a worker, I can see the mediaInfo is showing up correctly

```
    Megapixels: 2.1
  },
  mediaInfo: { '@ref': '', track: [ [Object], [Object], [Object] ] },
  hasClosedCaptions: false,
```

Please let us know if that specific process is not working for you, thanks.

**Comment by ferferga** [comment]
Okay, it seems that after upgrading (I was still sticking to the tdarr_arm and tdarr_node_arm images) and recreating my whole library, the plugin has the ``mediaInfo`` key exposed.
However, I still have the issue that Tdarr is trying to reprocess the outputted file through the plugin, which fails because mediaInfo is not available for it.

Here you have the plugin code untouched:
<details>

````
// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
module.exports.details = function details() {
  return {
    id: 'FvEYXDDRV',
    Name: 'A H264 si no es un códec moderno',
    Type: 'Video',
    Operation: 'Transcode',
    Description: '',
    Version: '',
    Link: ''
  };
};

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
const plugin = async (file) => {
  var response = {
    processFile: false,
    preset: '',
    container: '.mkv',
    handbrakeMode: false,
    ffmpegMode: true,
    reQueueAfter: false,
    removeFromDB: false,
    infoLog: ''
  };

  const excludedCodecs = ['vp9', 'rgb', 'avc'];
  let trackInfo = null;
  const fileName = file.meta.FileName;

  // Hacemos un loop ya que algunos archivos Tdarr los reconoce como de audio porque la pista de audio es la que
  // se encuentra en primer lugar, por lo que file.video_codec_name no es muy fiable, por lo que es mejor ir uno a uno.
  for (const track of file.mediaInfo.track) {
    if (track['@type'].toLowerCase() === 'video') {
      const codec = track.Format.toLowerCase();

      if (!excludedCodecs.includes(codec)) {
        trackInfo = track;
      }

      if (trackInfo !== null) {
        let parameters = '-map 0 -c copy -c:v libx264';
        const width = parseInt(trackInfo.Width);
        const height = parseInt(trackInfo.Height);
        let bitrate = Math.ceil(parseInt(trackInfo.BitRate) / 1000);

        // Para compensar la mejor eficiencia de HEVC sin perder mucha calidad, le añadimos un 50% más de bitrate.
        // Si el archivo tiene otro códec, lo dividimos a la mitad, ya que seguramente será un codec más antiguo y con
        // peor eficiencia.
        if (width <= 1920 && height <= 1080) {
          if (codec === 'hevc') {
            bitrate = bitrate * 1.5;
          } else {
            bitrate = bitrate * 0.5;
          }

          parameters += ' -b:v ' + bitrate.toString() + 'k';
          parameters += ' -movflags +faststart';
          response.preset = ', ' + parameters;
          response.infoLog =
            'Convirtiendo ' +
            fileName +
            " con los siguiente parámetros: '" +
            parameters +
            "'\n";
          response.processFile = true;
        }
      }

      break;
    }
  }

  if (response.infoLog === '') {
    response.infoLog =
      'El archivo ' +
      fileName +
      ' no necesita conversión ya que no cumple los criterios para ello\n';
  }

  return response;
};

module.exports.plugin = plugin;
````

</details>

**Comment by supersnellehenk** [comment]
You don't actually need mediaInfo for that plug-in. It's basically doing what Migz is doing with his CPU ffmpeg plug-in, just grab that one and add your arguments in code if you need.

**Comment by ferferga** [comment]
@supersnellehenk Can't share video, but you can try exporting raw video (no Prores, simple RGB) from Premiere or Vegas and check that codec_name and codec_tag_string sometimes appears as [0][0][0] or something along the lines of it. Some fields are also missing in those kind of videos. Some files that have audio codecs established as the first track are also bugged with ffprobe and categorised as "video" when in reality they're audio.

I simply want to stick with mediaInfo, that's it.

**Comment by supersnellehenk** [comment]
@ferferga  Ah, raw video. Yeah I haven't ran that through it, so couldn't tell.

> I still have the issue that Tdarr is trying to reprocess the outputted file through the plugin

Well that's just Tdarr and how the plugins work. Although, mediaInfo isn't available at all to a plugin if it's disabled as a scanner for the library apparently, but it does show it when you manually click on a file. 
![image](https://user-images.githubusercontent.com/25726058/147361903-1cbf08a3-343c-4353-9d52-d373052d55e8.png)
I enabled it there and your plugin worked fine.

**Comment by HaveAGitGat** [comment]
Yeah the `mediaInfo` scan is sometimes incredibly slow (in some cases it has to read the entire file which can take a few minutes) so it has to be optionally enabled as the other scan types generally only take a few seconds.

**Comment by HaveAGitGat** [comment]
Please re-open if needed

**Comment by ferferga** [comment]
@HaveAGitGat I don't think this issue warrants to be closed - I made a workaround for it, but this is a limitation that Tdarr has and should be solved, either by parsing mediaInfo on temp files or by adding to the response payload an option that makes it skip the same's plugins post-processing checks.

**Comment by HaveAGitGat** [comment]
I'm not sure what you mean,  the `file` object received in the plugin contains the latest data on the most recent cache file (or source file if the file has not been transcoded yet). It's scanned seconds beforehand.

So use `file.mediaInfo` to access the most recent mediaInfo data, or use `otherArguments.originalLibraryFile.mediaInfo` to access the original library file data.

Plugins are conditional, so the new file should meet the conditions of what the plugin is trying to achieve. Hence there is no need to skip the plugin stack cycling else there is something wrong with your plugin.

**Comment by HaveAGitGat** [comment]
A simple way to skip the plugin after transcoding has been done is to use this at the start of your plugin:

```
 console.log(file.file)
 console.log(otherArguments.originalLibraryFile.file)
if(file.file !== otherArguments.originalLibraryFile.file){
    response.infoLog += 'File has already been transcoded'
    respone.processFile = false;
    return response;
}
```

Example, original file is:
`C:/Transcode/source folder/SampleVideo_1280x720_1mb.mp4`

When plugin first runs, console logs will show:
```
C:/Transcode/source folder/SampleVideo_1280x720_1mb.mp4
C:/Transcode/source folder/SampleVideo_1280x720_1mb.mp4
```

After file has been transcoded, new file will re-enter plugin and console logs will show:
```
C:/Transcode/Cache Folder/SampleVideo_1280x720_1mb-TdarrCacheFile-hSDFXr1Pl.mkv
C:/Transcode/source folder/SampleVideo_1280x720_1mb.mp4
```

So the plugin will return ` 'File has already been transcoded`
