### ISSUE TITLE
plugin not showing data retrieved in call back to user in infoLog

### ISSUE THREAD

**Issue by goofballtech** [HaveAGitGat/Tdarr_Plugins#218]
moving from main repo per request....

Is your feature request related to a problem? Please describe.
I am writing a plugin that uses Plex's API to force a folder fresh after transcode rather than the other ones that need additional programs or dockers. In this plugin i hit the API of the plex server to refresh a given folder. The response then give a hint as to if the refresh was successful or not based on the response status codes. 200,, 401, 404, etc.

if i do the below, the responses in the check reply function are never added because TDarr has moved on before the request resolves (i'm assuming this piece since it works fine in node directly)

```javascript
    http.get(fullUrl, (res) => {
      checkReply(res.statusCode, redactedUrl)
      return response
    }).on('error', (e) => {
      response.infoLog += `We have encountered an error: ${e}`
      return response
    });
```

Describe the solution you'd like
i would like for the program to receive these response codes properly so i may added a success/error message to the user facing display.

Describe alternatives you've considered
i have tried a few different way to do it. Async/await, callbacks, or making my own new Promise.

Additional context
added a PR to plugins so the code can be viewed properly. HaveAGitGat/Tdarr_Plugins#217

**Comment by HaveAGitGat** [comment]
Plugins can be asynchronous so you can use async/await in them whereas the code you've written uses callbacks. For example this plugin uses async/await:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_z80t_keep_original_date.js#L68

**Comment by HaveAGitGat** [comment]
Fixed in this: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/217
