### ISSUE TITLE
Timestamps are unset in a packet for stream 0 - Conversion failed!

### ISSUE THREAD

**Issue by PhuriousGeorge** [HaveAGitGat/Tdarr_Plugins#219]
**Describe the bug**
Several of my older, hard to replace files and a few newer ones seem like they get through the transcode process, but fail out when combining streams back together:

>[matroska @ 0x55d5964567c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. >Fix your code to set the timestamps properly
>[matroska @ 0x55d5964567c0] Can't write packet with unknown timestamp
>av_interleaved_write_frame(): Invalid argument
>[matroska @ 0x55d5964567c0] Can't write packet with unknown timestamp
>Error writing trailer of /temp/BLAH BLAH LONG FILE NAME HERE-TdarrCacheFile-lYBY4PX-9.mkv: Invalid argument
>frame= 144 fps=0.0 q=-1.0 Lsize= 3kB time=00:00:06.00 bitrate= 4.2kbits/s speed=3.92e+03x 
>video:407kB audio:95kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> Conversion failed!

**To Reproduce**
Put one of the offending files through the stack again.

**Expected behavior**
Starting with an assumption (I know what that makes me...):
I've seen similar (probably on these files) when changing containers from mp4 to mkv in mkvtoolnix-gui.  I believe it calls it a warning and completes the job and the files have been use-able to this point.

Ultimately, it would be better to resolve the issue.  Google didn't turn too much up, but it seems common opinion is to append arguments to ffmpeg `-fflags +genpts` or `-ss` [Ref 1](https://video.stackexchange.com/questions/24462/timestamps-are-unset-in-a-packet-for-stream-0-this-is-deprecated-and-will-stop) & [Ref 2](https://stackoverflow.com/questions/66013483/cant-write-packet-with-unknown-timestamp-av-interleaved-write-frame-invalid).  I've no idea how to attempt this with Tdarr via altering the transcode plugin I would assume (again...)?

**Screenshots**

**Please provide the following information:**
- Config files:  Nothing relevant to the inquiry
- Log files:  Nothing relevant noted
- Worker error: Ref above
- Plugin Stack:
>Pre-processing - Tdarr_Plugin_lmg1_Reorder_Streams
>Pre-processing - Migz-Remove image formats from file
>Pre-processing - FFmpeg Tiered HEVC MKV
>Pre-processing - Migz-Remux container

 - OS: Docker (Linux)
 - Browser N/A
 - Version 2.00.12

**Comment by HaveAGitGat** [comment]
Could have a separate plugin for this. Else you'd need to add `-fflags +genpts` to every plugin which is potentially not intended behaviour.

**Comment by PhuriousGeorge** [comment]
Thanks for the reply. I think I've figured out the way these plugins work (mostly ref #226).  I'll leave these files hanging in the errored-out are and if there's enough piling up, I'll either pull them out to manually mend them or alter a plugin to follow-up the main transcode plugin.
