### ISSUE TITLE
Tdarr_Plugin_vdka_Tiered_CPU_CRF_Based_Configurable not obeying configuration

### ISSUE THREAD

**Issue by PhuriousGeorge** [HaveAGitGat/Tdarr_Plugins#226]
Over the last few days, I've switched over to [Tdarr_Plugin_vdka_Tiered_CPU_CRF_Based_Configurable](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_vdka_Tiered_CPU_CRF_Based_Configurable.js) as my main transcoding plugin, but have noticed that the configuration of this plugin isn't obeyed.

It wasn't until I noticed my SD & 4KUHD content was passing through untouched ( configuration set to `false`), that I realized none of my tuned settings were being obeyed. CRF, bframe, preset and SD/UHD bypass were all running at the coded defaults (which aren't what the tooltip claims they are :P).  I've confirmed my plugin with the Raw from GH and nothing appears amiss.

I've locally made a few copies of the plugin and set my preferences as the default variables to keep things going, but there's something fishy going on and I've not quite figured it out yet.

**Comment by HaveAGitGat** [comment]
Seems the examples were being used, I've updated the default values.

Are you saying there's something wrong with the inputs or the transcode logic? Inputs are coming through fine for me.

**Comment by PhuriousGeorge** [comment]
Not sure if something was amiss with my rig or what was going on.  I replicated the failure multiple times before enforcing my own defaults.

Regardless, I've started and stopped a range of transcodes with differing settings and resolutions and it appears to be working as intended currently.

**Comment by PhuriousGeorge** [comment]
I take my prior statement back. sdDisabled is set to false and Tdarr just spit out about 100 files as not requiring transcoding:

Pre-processing - Remove Data Streams
☑File has no data streams!
☑File meets conditions!
Pre-processing - Tdarr_Plugin_lmg1_Reorder_Streams
File has video in first stream
File meets conditions!
Pre-processing - Migz-Remove image formats from file
☑File doesn't contain any unwanted image format streams.
Pre-processing - Tiered FFMPEG CPU CRF Based Configurable
☑File is a video!
_**☒File is SD, not processing**_
Pre-processing - Migz-Remux container
☑File is already in mkv container.
undefined

The other configured settings do appear to be working

**Comment by HaveAGitGat** [comment]
Thanks, fixed with this: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/241
