### ISSUE TITLE
Winsome H265 10 bit burning subtitles into video stream

### ISSUE THREAD

**Issue by lordairivis** [HaveAGitGat/Tdarr_Plugins#23]
2019-12-16: Please note I'm on a 2 week break. Sorry for the inconvenience.

Not sure if it's a configuration issue or not, but the Winsome H265 10 bit plugin is burning the English SDH subtitle stream into transcoded video. The preset string in the plugin is listed as ```response.preset = '-Z "H.265 MKV 2160p60" -e x265_10bit --all-audio --all-subtitles'```, which does not appear to have any of the burn-in options enabled (e.g. ```--subtitle-burned```, ```--srt-burn```), however, the first subtitle track for certain video files I am attempting to transcode (in this case, the English SDH track) is being burned into the video stream rather than simply being copied over. I would like to preserve the subtitle tracks where ever possible so I have the option to turn them on.

**Comment by HaveAGitGat** [comment]
Perhaps it's an issue with the format/codec of the files you're using? FFmpeg doesn't support everything so maybe it's burning in the subtitles as a last resort. This is an ffmpeg issue so might be worth asking on an ffmpeg forum and then modifying the plugin command if necessary.

You can copy the plugin into your local plugins and configure it however you like.

**Comment by HaveAGitGat** [comment]
Please re-open if you still need help

**Comment by lordairivis** [comment]
I figured this issue out. It's the default behavior of HandBrake to burn the first subtitle track in. This option can apparently only be changed through the GUI, which I do not use since my instance of Tdarr is running on a headless Ubuntu VM. There does not appear to be any way to change this behavior without the GUI, so I guess I will just have to deal with stripping the subtitle tracks before encode to avoid burning the subtitles into the video.
