### ISSUE TITLE
Tdarr_Plugin_MC93_Migz2CleanTitle sets title to literally double quotes (`""`)

### ISSUE THREAD

**Issue by YodaDaCoda** [HaveAGitGat/Tdarr_Plugins#231]
`Tdarr_Plugin_MC93_Migz2CleanTitle` inadvertently sets the title to `""` instead of an empty string or removing it entirely.

**Comment by HaveAGitGat** [comment]
Fixed https://github.com/HaveAGitGat/Tdarr_Plugins/pull/232
