### ISSUE TITLE
Tdarr_Plugin_Mthr_VaapiHEVCTranscode fails when bitrate cutoff is not met

### ISSUE THREAD

**Issue by vtruong68** [HaveAGitGat/Tdarr_Plugins#245]
Below is the info snippet of a 6662kbps file that doesn't meet my bitrate cutoff. My remuxOnly variable is set to false.
```
Pre-processing - FFMPEG VAAPI HEVC Transcode
☒ Input file's bitrate 6662 is lower than the minimum bitrate threshold of 8000. Skipping this plugin.
☑ Stream analysis complete, processing required.
```

I would expect this to result in the "Transcode: Success/Not Required", however, it's ending up in the "Transcode: Error/Cancelled" instead with the following error:
```
The new transcode arguments were the exact same as the last ones meaning
the file/worker would most likely be stuck in an infinite transcode loop if not stopped.
Last arguments: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi ,-map 0:v -map 0:a -map 0:s? -map 0:d? -map 0:t? -c copy
New arguments: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi ,-map 0:v -map 0:a -map 0:s? -map 0:d? -map 0:t? -c copy
Plugin Community Tdarr_Plugin_Mthr_VaapiHEVCTranscode
```
What's causing this plugin to error out and run the same argument multiple times?

**Comment by vtruong68** [comment]
Since the file is being processed despite the "Skipping this plugin." part, would the fix be to move line 81 to after where line 107 is? That seems to be work for me in my local copy.

I'm not sure if processing should still happen when criteria isn't met, but I would think not.

**Comment by HaveAGitGat** [comment]
Sorry for delay, please post the job report https://docs.tdarr.io/docs/other/job-reports/ and reopen if needed thanks.
