### ISSUE TITLE
Crop and Interlace detect

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr_Plugins#25]
I would like to add to the "nosirus" plugin the auto crop and the interlacing detection so that it adds the yadif=1 mode by itself.

Is it possible?

**Comment by HaveAGitGat** [comment]
Hi, yes you can copy the plugin to your local plugins folder and configure it how you like.

**Comment by Nosirus** [comment]
the use of ffProbeData with interlaced_frame would allow to know if the file is inerlaced? in order to adapt the encoding parameters

for the crop I'm trying to use... 
-vf cropdetect=24:16:10 -f null - 2>&1 | awk '/crop/ { print $NF }' | tail -1
unsuccessfully

**Comment by Nosirus** [comment]
I'm still looking into getting into autocrop based on that command.

crop=`ffmpeg -i $1 -t 1 -vf cropdetect -f null - 2>&1 | awk '/crop/ { print $NF }' | tail -1`

but with the input and output I'm blocking

**Comment by controlol** [comment]
I created a plugin that can crop, this command will not work properly because it only has one value. During movies and series it often gets bad values because if it has a dark scene the crop will be wrongly determined.

**Comment by HaveAGitGat** [comment]
Will close this due to @controlol 's comment.
