### ISSUE TITLE
Error 2436115: Invalid argument

### ISSUE THREAD

**Issue by Fribb** [HaveAGitGat/Tdarr_Plugins#274]
in the following line https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only.js#L264

there is a space missing which will result in 

`-maxrate 4524213-minrate 2436115`  but it should be `-maxrate 4524213 -minrate 2436115`

**Comment by HaveAGitGat** [comment]
Fixed, thanks.
