### ISSUE TITLE
Tdarr_Plugin_sdd3_remove_commentary_tracks.js broken

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#277]
I have been running this plugin for year+, without problems. Over the past weeks Im experiencing issues.
Maybe the problem arised when this plugin was updated 25 days ago with the dispoition comment flag.

My issue:
I have a file that has subrip/srt element with the title 'commentary'.
The plugin recognized this as a commentary track:

Debug:
darr_Plugin_sdd3_Remove_Commentary_Tracks - Pre-processing
☒test tags codectype = subtitle.
☒test disposition.comment = 0.
☒File contains commentary tracks. Removing!

It tried to re-code, but clearly fails as the subtitle with the  'commentary track' is not actually removed; so it keep trying the same file over and over again.
and it also removes the wrong audio tracks (as it assume it's an audio track, but actually it in a subtitle);

The solution is 
1. either to change to the plug to only process codec-types 'audio'

or 
2. have the plugin remove audio and srt with the word  'commentary'; 

In both situations the below current code needs updating.

      if (
        file.ffProbeData.streams[i].codec_type.toLowerCase() == "audio" &&
        file.ffProbeData.streams[i].disposition.comment == 1 ||
        file.ffProbeData.streams[i].tags.title
          .toLowerCase()
          .includes("commentary")
      ) {
        ffmpegCommandInsert += ` -map -0:a:${audioIdx}`;

Solution for option 1 seems to be :
      if (
        file.ffProbeData.streams[i].codec_type.toLowerCase() == "audio" &&
        file.ffProbeData.streams[i].disposition.comment == 1 ||
        file.ffProbeData.streams[i].codec_type.toLowerCase() == "audio" &&
        file.ffProbeData.streams[i].tags.title
          .toLowerCase()
          .includes("commentary")
      ) {
        ffmpegCommandInsert += ` -map -0:a:${audioIdx}`;

**Comment by DoNotResuscitate** [comment]
Looks like this still hasn't been fixed...
