### ISSUE TITLE
Remove english audio tracks

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr_Plugins#29]
https://www.reddit.com/r/Tdarr/comments/efuc30/remove_english_audio_tracks/

**Comment by Migz93** [comment]
@HaveAGitGat we can probably close this issue now as theres a couple plugins that can do this.

**Comment by supersnellehenk** [comment]
@csandman https://github.com/HaveAGitGat/Tdarr_Plugins/blob/29f23fadbfe8c2509941a7790ee909948e2d2a9b/Community/Tdarr_Plugin_henk_Keep_Native_Lang_Plus_Eng.js and please don't resurrect issues that are this old

**Comment by csandman** [comment]
Well that's exactly what I'm looking for, thanks a lot!  And sorry for bringing back an old issue.
