### ISSUE TITLE
just aac and x265?

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr_Plugins#3]
Hi,

I would like to reencode my library and I think a plugin would be the best.

If it's not in AAC reencode audio and if it's not in x265 same 

while keeping all the tracks regardless of the language (a lot of Japanese korean) and all the subtitles.

but I'm not very competent, help would be welcome:(

**Comment by HaveAGitGat** [comment]
Hi I'll take a look at doing this after I've released the new update today

**Comment by HaveAGitGat** [comment]
@Nosirus 

Are you able to fill out the following:

 `Video transcode requirements: (E.g convert using H265 using HandBrake's 'H.265 MKV 1080p30' preset. Specify an FFmpeg command if you're wanting to use that.)

Video audio track requirements:  (E.g add 192Kbit AAC if track doesn't exist)

Subtitles: (Keep/Remove)

Title meta-data or other: (Keep/Remove)

Output container: (Same as original/MP4/MKV etc)

Any other comments: `

Thanks

**Comment by Nosirus** [comment]
Sure

Video transcode requirements: i use -e x265 -q 22 --encoder-preset slow -x aq-mode=3

Video audio track requirements:  -E fdk_aac -Q 4

Subtitles: (Keep/Remove): keep

Title meta-data or other: (Keep/Remove): remove, I was looking if it was possible to remove the attachments, it happens that there are images in the mkv, I have not yet found the command

Output container: mkv

Any other comments: 
I use this command most often, I don't know if copy:aac really works though to avoid reencoding the aac
-e x265 -q 22 --encoder-preset slow --all-audio --all-subtitles copy:aac -E fdk_aac -Q 4 -x aq-mode=3

ps: Thanks for Tdarr and your help, I love this software it's really what I miss!

**Comment by HaveAGitGat** [comment]
Thanks, sorry had a busy weekend sorting out some issues with the latest update but will try and do this soon.

You can do most of what you want using the plugin creator. Add a ‘Filter’ plugin to prevent transcoding files which are already in h265 (hevc). Put that plugin at the top of the stack. 

Then create a transcode plugin in the plugin creator using your video encoding command.

And then add the community plugin to remove meta data. 

The only extra thing is making sure there is aac audio.

You can try the above if you want to play around with some test files until I make the full plugin 👍

**Comment by HaveAGitGat** [comment]
You didn't mention if you're wanting to use HandBrake or FFmpeg but I'm assuming HandBrake.

There's a new community plugin:
Tdarr_Plugin_b38x_Nosirus_h265_aac_no_meta

Update your plugins and give it a try :)

**Comment by Nosirus** [comment]
Great, thank you so much!

but, if the file is already in hevc it only keeps the first audio track and subtitle, can we make it keep everything?

Another question, I don't know if it's possible, encode in aac, even if it's already in hevc? so he can check the codec of the audio track?

This would avoid re-encoding from aac to aac and re-encoding the audio even of files already in hevc

I'm trying to understand the principle so I won't have to bother you :) (and sorry for my English...)

**Comment by HaveAGitGat** [comment]
Sure I’ll do that later today.

Which language track do you want it to encode into aac? Any?

**Comment by Nosirus** [comment]
I spent a few hours trying to figure out
`
function details() {

  return {
    id: "Tdarr_Plugin_b38x_Nosirus_h265_aac_no_meta",
    Name: "Nosirus h265, aac, no meta, subs kept",
    Type: "Video",
    Description: `If the file is not in h265 it will be trancoded into h265 with HandBrake using the following command '-e x265 -q 22 --encoder-preset slow --all-audio --all-subtitles copy:aac -E fdk_aac -Q 4 -x aq-mode=3'. If no aac, aac track will be added. Subtitles are kept. Metadata is removed.\n\n
`,
    Version: "1.00",
    Link: "https://github.com/HaveAGitGat/Tdarr_Plugin_b38x_Nosirus_h265_aac_no_meta"
  }

}

function plugin(file) {


  //Must return this object

  var response = {

     processFile : false,
     preset : '',
     container : '.mp4',
     handBrakeMode : false,
     FFmpegMode : false,
     reQueueAfter : false,
     infoLog : '',

  }


  if (file.fileMedium !== "video") {


    console.log("File is not video")

    response.infoLog += "☒File is not video \n"
    response.processFile = false;

    return response

  } else { 

     var jsonString = JSON.stringify(file)


     if(file.ffProbeData.streams[0].codec_name != 'hevc'){

        response.processFile = true;
        response.preset = '-sn, -map 0 -c:v libx265 -preset:v slow -pix_fmt yuv420p10le -x265-params "crf=22:aq-mode=3"'
        response.container = '.mkv'
        response.FFmpegMode = true
        response.reQueueAfter = true;
        response.infoLog += "☒File is not in hevc! \n"
        return response

     }else{
      response.infoLog += "☑File is already in hevc! \n"
     }
	 
	 if(!jsonString.includes("aac")){

      response.infoLog += "☒File has no aac track \n"
      response.preset = ',-map 0 -c copy -c:a aac -vbr 4'
      response.container = '.mkv'
      response.reQueueAfter = true;
      response.processFile = true;
	  response.FFmpegMode = true
      return response

     }else{
      response.infoLog += "☑File has aac track \n"
     }


     if(file.meta.Title != undefined ){

      response.infoLog += "☒File has title metadata \n"
      response.preset = ',-metadata title="" -metadata comment="" -map 0 -c copy'
	  response.container = '.mkv'
      response.reQueueAfter = true;
      response.processFile = true;
      response.FFmpegMode = true
      return response
     }else{
      response.infoLog += "☑File has no title metadata \n"
     }


     response.infoLog += "☑File meets conditions! \n"
     return response

  }
}

module.exports.details = details;

module.exports.plugin = plugin;
`
I want to keep all languages, I have a lot of foreign video, I have modified to keep the metadata (otherwise the audio and subtitle languages disappears) but removed the title and comments

just one last problem, if I have two different audio codec tracks (aac and ac3) it doesn't encode the ac3 track, any ideas?

**Comment by HaveAGitGat** [comment]
Nice work, use this when converting audio to aac:

`-map 0:v? -map 0:a? -map 0:s? -map 0:d? -c:v copy -c:a aac -vbr 4 -c:s copy -c:d copy `

The reason it wasn't working for you is because you were mapping all streams to '-c copy' so it was copying all streams and then by default only converting the first audio stream.

The problem with your plugin now is that it won't convert audio to aac if already one aac stream exists. Do you want it like that?

**Comment by Nosirus** [comment]
Thank you for the command, I thought -map 0 allowed to pass all the streams

No, I would like it to convert all audio streams, if there is already one aac stream, ignore it and re-encode the others streams

**Comment by HaveAGitGat** [comment]
Yeah you're right I just prefer stating all the different stream types, you could have done this:
`
-map 0 -c:v copy -c:a aac -vbr 4 -c:s copy -c:d copy `

Same result.

> No, I would like it to convert all audio streams, if there is already one aac stream, ignore it and re-encode the others streams

Ok well at the moment the plugin will only encode aac streams if no aac streams are found. It gets a bit trickier  with what you're wanting to do as you have to create a dynamic ffmpeg command.

For example, lets say the first audio stream is aac and the second isn't. You'd use this command:

`,-map 0 -c:v copy  -c:a copy -c:a:1 aac -vbr 4 -c:s copy -c:d copy`

Or if the 3rd and 4th streams weren't aac you'd use this:

`,-map 0 -c:v copy  -c:a copy -c:a:2 aac -vbr 4 c:a:3 aac -vbr 4 -c:s copy -c:d copy`

Have a look at line 71 of this plugin to get an example of iterating through the streams. You'd need to check which audio streams are aac.

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_s7x8_winsome_h265.js

Like this:



```
var audioIdx = -1
var ffmpegCommandInsert = ''
var hasnonAACTrack = false

for (var i = 0; i < file.ffProbeData.streams.length; i++) {

    try {
        if (file.ffProbeData.streams[i].codec_type.toLowerCase() == "audio") {
            audioIdx++
        }
    } catch (err) { }


    try {
        if (file.ffProbeData.streams[i].codec_name !== 'aac') {
            ffmpegCommandInsert += ` -c:a:{audioIdx}1 aac -vbr 4 `
            hasnonAACTrack = true

        }
    } catch (err) { }

}

var ffmpegCommand = `,-map 0 -c:v copy  -c:a copy ${ffmpegCommandInsert} -c:s copy -c:d copy`

if (hasnonAACTrack == true) {

    response.processFile = true;
    response.preset = ffmpegCommand
    response.container = '.mkv'
    response.handBrakeMode = false
    response.FFmpegMode = true
    response.reQueueAfter = true;
    response.infoLog += "☒ File has audio which is not in aac! \n"
    return response



}

```

**Comment by HaveAGitGat** [comment]
That should do what you want, you can remove this part from your original plugin:

```
 if(!jsonString.includes("aac")){

  response.infoLog += "☒File has no aac track \n"
  response.preset = ',-map 0 -c copy -c:a aac -vbr 4'
  response.container = '.mkv'
  response.reQueueAfter = true;
  response.processFile = true;
  response.FFmpegMode = true
  return response

 }else{
  response.infoLog += "☑File has aac track \n"
 }
```

**Comment by HaveAGitGat** [comment]
@Nosirus  I have updated the community plugin and tested it a few times and it seems to work well. Have a test.

**Comment by Nosirus** [comment]
fantastic, I just did some tests too, it seems to be perfect!

really a big thank for your time and help :) I really look forward to seeing your project continue to grow!

**Comment by HaveAGitGat** [comment]
No problem!

Yes ffmpeg can detect the number of channels, I’m not sure how it adapts the encoding rate though. And I haven’t looked into libfdk_aac. Which platform are you using Tdarr on? Windows, Docker?

**Comment by Nosirus** [comment]
Docker on Unraid

**Comment by HaveAGitGat** [comment]
@Nosirus  Are you still needing help with this?

**Comment by Nosirus** [comment]
No thank you :)
