### ISSUE TITLE
Tdarr_Plugin_NIfPZuCLU_2_Pass_Loudnorm_Audio_Normalisation

### ISSUE THREAD

**Issue by exodus454** [HaveAGitGat/Tdarr_Plugins#303]
Plugin won't run, error:
Plugin error! Error: Command failed: ffprobe -v quiet -print_format json -show_format -show_streams "/library/shows/.mkv"

/bin/sh: 1: ffprobe: not found

Not sure why it isn't found, ffprobe runs fine with everything else.
Running beta 2.00.15

**Comment by HaveAGitGat** [comment]
This plugin was updated so this should no longer be a problem when running Tdarr 2.00.16+
