### ISSUE TITLE
[Bug] Mjpeg Stream - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zero77** [HaveAGitGat/Tdarr_Plugins#334]
I am using Tdarr 2.00.18 on Debian and i am getting the below error for all files:
Also, below are the transcode options i am using:

![image](https://user-images.githubusercontent.com/16563034/192252287-482a0fb9-bcf8-45f4-8986-680a78114402.png)

![image](https://user-images.githubusercontent.com/16563034/192253164-940e07d1-0df5-485d-a9a7-10b5ce6d8c22.png)

**Comment by supersnellehenk** [comment]
This seems like an improper cache setup. You need a shared cache between the server and node.
