### ISSUE TITLE
Filtering queues by library does not work as expected

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr_Plugins#358]
It seems that trying to filter one of the queues by typing the library name into the manual entry field does not work, what does work is entering the DB name found by clicking one of the files, I would expect that the user defined name would be the proper entry for this filter.

The time field behaves similarly, although I can't figure out how to get that to filter at all.

No filter
![image](https://user-images.githubusercontent.com/11021632/209034970-eee8fdb3-e022-41a0-9cc8-bb3cb6561654.png)

"Testing" as filter (I would expect this to work)
![image](https://user-images.githubusercontent.com/11021632/209035034-51431f18-4ad4-430b-b755-5b6b5762ed63.png)

"eUuRSLI5y" as filter (This could still work, but the name should work too.)
![image](https://user-images.githubusercontent.com/11021632/209035096-7f854c02-550f-4c2c-96a5-389069e4d4c2.png)

Time filter doesn't seem to work at all.
![image](https://user-images.githubusercontent.com/11021632/209035227-134401e4-1c86-4989-b558-a1a52e111380.png)

**Comment by HaveAGitGat** [comment]
Fixed in .19
