### ISSUE TITLE
Add new plugin to create local copy of original file when using NFS (or any other network share)

### ISSUE THREAD

**Issue by ejalal** [HaveAGitGat/Tdarr_Plugins#361]
Hello

As stated in the title, I would like a simple plugin to copy the original files as is locally with a simple copy (as they are on an NFS share) to speed up the transcoding.

The issue I'm having currently is that my instance is not fully using my nvidia card as it's slowed down by network traffic to slowly get the the file while transcoding, also pushing the transcoded file blocks everything as it slows down the whole network and transcoding of other files is completely stuck why the file is copied back to NSF

**Comment by ejalal** [comment]
I just made my own, with a mix of a "Tdarr_Plugin_00td_action_remux_container" and "Tdarr_Plugin_00td_filter_break_stack_if_processed" plugins so it stops after first loop.

It solves the problem where current transcode speed isn't impacted at all as it transcodes the local cache file, but still has an impact on "copies" in progress when manually accept a transcode as the NFS transfer speed goes down. I might need to tweak by NFS settings at some point.

If someone is interested I can publish this plugin.

**Comment by HaveAGitGat** [comment]
With Tdarr Flows you can copy to working directory e.g.:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/2e0d0f0d-5156-43aa-a558-286b04d8381f)
