### ISSUE TITLE
[Plugin Request] Plugin to set the first audio track as default

### ISSUE THREAD

**Issue by anym001** [HaveAGitGat/Tdarr_Plugins#369]
There is already a plugin with which you can mark an audio stream as default. (Tdarr_Plugin_c0r1_SetDefaultAudioStream)
However, default is only set for a certain number of channels. 

It would be great if default flag is always set at the first audio stream and removed at all others.

**Comment by anym001** [comment]
I tinkered around a bit myself and came up with a possible solution for such a plugin. 
Perhaps someone could check this more closely and then publish accordingly. 

Basis was the plugin Tdarr_Plugin_c0r1_SetDefaultAudioStream.

[plugin.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/10556357/plugin.txt)

**Comment by tws101** [comment]
[Tdarr_Plugin_c0r1_SetDefaultAudioStream.zip](https://github.com/HaveAGitGat/Tdarr_Plugins/files/12323695/Tdarr_Plugin_c0r1_SetDefaultAudioStream.zip)

Here is a cleaned up copy, incremented version by one and simplified processing with functions.  Also removed all var and used let and const

I you should test that and if it works fine proceed with a pull request if you want it published

****Please note that my changes are largely untested and should be used at your own risk****

**Comment by tws101** [comment]
I missed that present needed a comma

preset: '',

need to be 

preset: ' , ',

**Comment by anym001** [comment]
Thank you for clean up this plugin @tws101 
I have tested this and create a pull request. 
[https://github.com/HaveAGitGat/Tdarr_Plugins/pull/445](url)
