### ISSUE TITLE
Tdarr_Plugin_MC93_Migz3CleanAudio running total bug

### ISSUE THREAD

**Issue by f16v1per** [HaveAGitGat/Tdarr_Plugins#370]
I recently ran into an issue with the Migz3CleanAudio plugin not removing audio tracks that were unwanted.  After looking into the Tdarr transcoding report I noticed that the `0:a:3` audio index was being listed twice.

```
26 2023-02-05T22:03:53.447Z Pre-processing - Migz-Clean audio streams
27 2023-02-05T22:03:53.447Z ☒Audio stream 0:a:0 has unwanted language tag fre, removing.
28 2023-02-05T22:03:53.447Z ☒Audio stream 0:a:1 detected as being descriptive, removing.
29 2023-02-05T22:03:53.447Z ☒Audio stream 0:a:3 has unwanted language tag fre, removing.
30 2023-02-05T22:03:53.447Z ☒Audio stream 0:a:3 detected as being descriptive, removing.
31 2023-02-05T22:03:53.447Z ☒Cancelling plugin otherwise all audio tracks would be removed.
```

I started looking through this script and saw it kept a running total when it detected a audio stream name contained an unwanted string.  In this case, the audio stream `"title":"French - Audio Description" ` was being listed twice because it contained an unwanted language and was listed as commentary.   Since it was being flagged twice, it was also increasing the `audioStreamsRemoved` running total twice. This results in the running total equaling the number audio streams and preventing the script from removing the unwanted audio streams.  

The first fix I tried involved searching for the string of the audio index in the removal command and then subtracting 1 from the running total if it returned true.  But it realized the way I implemented it also counts audio tracks that were added only by the commentary check as being duplicate.  The simpler solution I came up with involves adding a boolean variable to flag the audio channel for removal and moving the running total counter and command insert lines to a separate if statement outside of the two checks that's triggered by the boolean variable.  This way regardless if the audio track is commentary or descriptive it only gets added to the removal command and audio tracks removed running total once.
   
 I tested this against the same file that contained the double counted audio stream and it was successfully removed.
 
 ```31 2023-02-06T20:25:53.514Z Pre-processing - Migz-Clean audio streams
32 2023-02-06T20:25:53.514Z ☒Audio stream French 0:a:0 has unwanted language tag fre, removing.
33 2023-02-06T20:25:53.514Z ☒Audio stream English - Audio Description 0:a:1 detected as being descriptive, removing. 0:a:1
34 2023-02-06T20:25:53.514Z ☒Audio stream English - Audio Description 0:a:1 detected as being descriptive, and has been previously added to the removal list.
35 2023-02-06T20:25:53.514Z ☒Audio stream French - Audio Description 0:a:3 has unwanted language tag fre, removing.
36 2023-02-06T20:25:53.514Z ☒Audio stream French - Audio Description 0:a:3 detected as being descriptive, removing. 0:a:3
37 2023-02-06T20:25:53.514Z ☒Audio stream French - Audio Description 0:a:3 detected as being descriptive, and has been previously added to the removal list.
```

**Comment by HaveAGitGat** [comment]
Merged, the PR, thanks.
