### ISSUE TITLE
Parameter in "file" for the name of the new file

### ISSUE THREAD

**Issue by ErikVogelLUH** [HaveAGitGat/Tdarr_Plugins#373]
I want to use mkclean to optimise my files after transcoding. I have a local installation I can use. I just cannot figure out, how to write a plugin which gives mkclean the proper exit file name, so that the Tdarr server can find the file after processing. Can anybody help me out?

**Comment by HaveAGitGat** [comment]
You'd use `file._id` for `file.file`  (both same).

**Comment by ErikVogelLUH** [comment]
So I call mkclean with file._id as the input and file.file as the output? Like this `mkclean --remux --optimize "${file._id}" "${file.file}"`?

I don't think I understood

**Comment by HaveAGitGat** [comment]
No file._id and file.file are the exact same. 

![image](https://user-images.githubusercontent.com/43864057/220527679-c6d18f50-6985-411a-a3a6-31d19b128179.png)

You can see file properties by clicking on the the file name on the Tdarr tab.

![image](https://user-images.githubusercontent.com/43864057/220527781-74418f03-16d5-4a56-8f60-a1411527f7f6.png)

**Comment by ErikVogelLUH** [comment]
Ok, so I cannot use `file.file` as the output file because it would be the same as the input file. But which path can I give mkclean as the output file so that tdarr can find it after it is processed by mkclean?

**Comment by HaveAGitGat** [comment]
I think the best solution for this would be to use a post processing plugin which can then feed the new file back to tdarr. For example take a look at this one:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_z18t_rename_files_based_on_codec_and_resolution.js

So could do something like 

```
// eslint-disable-next-line no-unused-vars
const plugin = (file, librarySettings, inputs, otherArguments) => {
  const lib = require('../methods/lib')();
  // eslint-disable-next-line no-unused-vars,no-param-reassign
  inputs = lib.loadDefaultValues(inputs, details);
  try {
    const fs = require('fs');
    const childProcess = require('child_process');

    const fileNameOld = file._id;

    // add -temp to new file name
    const parts = file._id.split('.');
    parts[parts.length - 2] + '-temp'
    const fileNameNew = parts.join('.');


    // run mkclean
    try {
      childProcess.spawnSync(
        'mkclean',
        [
          '--remux',
          '--optimize',
          fileNameOld,
          fileNameNew
        ],
      );
      console.log('success!')
    } catch (err) {
      console.log('error!')
      console.log(err)
    }

    // overwrite old file with new file
    fs.renameSync(fileNameNew, fileNameOld, {
      overwrite: true,
    });

    const response = {
      file,
      removeFromDB: false,
      updateDB: true,
    };
    return response;
  } catch (err) {
    // eslint-disable-next-line no-console
    console.log(err);
  }

  return undefined;
};
```

**Comment by HaveAGitGat** [comment]
You can now do this more simply with Tdarr Flows. E.g. here mkvpropedit is run on the file after transcoding:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/e1ba9bb5-9238-4113-a3d2-f1086e347c4b)
