### ISSUE TITLE
Tdarr_Plugin_MC93_Migz2CleanTitle.js Question

### ISSUE THREAD

**Issue by Swiftnesses** [HaveAGitGat/Tdarr_Plugins#377]
Good day,

Until now I've mainly been using the Migz Nvidia GPU plugin to convert 264, to 265. I've recently added this plugin to my stack, and it made me wonder, does Tdarr_Plugin_MC93_Migz2CleanTitle.js perform video transcoding using only my CPU? In which case I'm losing the value of my GPU...? Apologies if this is a stupid question.

**Comment by HaveAGitGat** [comment]
Yes that's right. The plugin is running commands such as ` -metadata:s:a:${audioIdx} title= ` to strip file metadata. It's not possible to use GPU for this. This is not a very CPU intensive operation so is normally limited by disk read/write speed.
