### ISSUE TITLE
Plugin request

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr_Plugins#4]
https://forums.unraid.net/topic/84070-support-haveagitgat-tdarr-audiovideo-library-analytics-transcode-automation/?do=findComment&comment=789469

> Can anyone offer advice on creating plugins?
> 
> What I want to create seems simple enough.
> 
> I want to convert any video file that has surround sound that isn't ac3, aac, or mp3, and transcode to ac3, and copy the rest (video, subtitles, etc).
> 
> It's late here and I'll have another crack at it on the weekend, just thought if someone could steer me in the right direction.
> 
>  
> 
> tl;dr, I have 10 year old surround sound that doesn't support DD+, DTS-HD, and most other modern surround sound files. As a result, I want to convert my videos with surround sound audio to something that will play on my speakers.
> 
>  
> 
> Thanks
>

**Comment by the1poet** [comment]
Thanks for posting this and following it and creating this for me.
So from my reply in the forum, I'd like anything surround sound that's not ac3 to be converted to ac3, and to not touch the video and subs.

**Comment by the1poet** [comment]
Can what you're doing check the video for audio type and number of channels and ignore others?

**Comment by HaveAGitGat** [comment]
Yes sure, I'll do that in the next couple of hours or so

**Comment by HaveAGitGat** [comment]
@the1poet 

Theres a new community plugin for you. Give it a test:
Tdarr_Plugin_b39x_the1poet_surround_sound_to_ac3

**Comment by the1poet** [comment]
not at home, but will give you an update when i am. thx so much!
