### ISSUE TITLE
Limit CPU Threads

### ISSUE THREAD

**Issue by Jessomadic** [HaveAGitGat/Tdarr_Plugins#411]
Possibly add the ability to change how many threads are being used as a menu option in Tdarr. Would be nice to have it running overnight and in the morning be able to lower the threads on whatever its working on to have more of my CPU to do work on

**Comment by HaveAGitGat** [comment]
Think a few people have done this by pinning Docker cores so would depend on how you’re running it.

**Comment by Jessomadic** [comment]
Using Windows but I could just to Affinity would be nice to have it in the web view but not a huge thing
