### ISSUE TITLE
Tdarr_Plugin_075a_Transcode_Customisable - Error TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by karl0ss** [HaveAGitGat/Tdarr_Plugins#413]
Want to start by saying how amazing this software is, but I have come into a bit of an issue, I am using the above plugin and passing in my own preset in json form (stored with the node.exe file) everything seems to work ok, and I can see the completed video in my Transcode Cache dir, and looking at the file it seems good and is exactly the same size as the same file done locally via handbreak, but the script is failing with the above error at the end of the encode,  attached is the log from the execution, hope it can show what I am doing wrong.

Thanks
[zU9OjB_sc-log.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/11508082/zU9OjB_sc-log.txt)

**Comment by HaveAGitGat** [comment]
Hey glad you’ve found it of use. Busy week but feel free to reopen if you still have trouble.

**Comment by karl0ss** [comment]
Yeah, the issue was me, my mount on the server for /mnt/TC has been unmounted...

great software mate :)
