### ISSUE TITLE
footprintId identical regardless of file

### ISSUE THREAD

**Issue by UnknownWitcher** [HaveAGitGat/Tdarr_Plugins#415]
Is the footprintId suppose to be identical for each file processed?

When I print `otherArguments.originalLibraryFile.footprintId` to the logs it's identicaly across multiple files, I originally wanted to use this as a way to lock a plugin and prevent infinit loops, here is how I create this file.

```
        var cacheFile = path.resolve(
            librarySettings.cache,
            `${
                details().id
            }.${
                otherArguments.originalLibraryFile.footprintId
            }`
        );
```

However, I just noticed that if multiple files get processed at the same time, then the footprintId will be the same as the first file that started the process, even though the footprint is shown to be different in the report. I'm running version 2.00.20

`2023-05-24T12:28:49.701Z "footprintId": "5q0gRb9jRC"`

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/82295355/bb1c1cd2-1cf4-464b-af62-9cb1d035a03b)

**Comment by HaveAGitGat** [comment]
Yeah the `otherArguments.originalLibraryFile.footprintId` will stay the same for a file from when it's first scanned as it's just a way of tracking the same file through Tdarr so can easily gather all the job reports for that specific file. It's randomly generated when the file is first scanned.

**Comment by HaveAGitGat** [comment]
Thanks, I tried to replicate this but got different results. So I added a console log of the footprintId and filename at the start of the plugin (was just using the default migz GPU plugin):

```
const plugin = (file, librarySettings, inputs, otherArguments) => {
  console.log(otherArguments.originalLibraryFile.footprintId + ': ' + otherArguments.originalLibraryFile.file)
```

I then started 3 workers and got this:

```
aYvpTVV2CK: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video.mp4
1Ra_kUvXz: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (3).mp4
mmpFGqEd0s: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy.mp4
aYvpTVV2CK: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video.mp4
dctsVOrGe8: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (4).mp4
1Ra_kUvXz: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (3).mp4
2U4U1-562: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (2).mp4
mmpFGqEd0s: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy.mp4
dctsVOrGe8: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (4).mp4
2U4U1-562: C:/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (2).mp4
```

Then sorted it in excel:

```
1Ra_kUvXz	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (3).mp4
1Ra_kUvXz	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (3).mp4
2U4U1-562	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (2).mp4
2U4U1-562	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (2).mp4
aYvpTVV2CK	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video.mp4
aYvpTVV2CK	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video.mp4
dctsVOrGe8	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (4).mp4
dctsVOrGe8	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy (4).mp4
mmpFGqEd0s	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy.mp4
mmpFGqEd0s	 C	/Transcode/Source Folder/sample__1080__libx264__aac__30s__video - Copy.mp4
```

So from what I can see, each footprintId is unique to each `originalLibraryFile.file`.


How were you checking the footprintIds? 

If you were doing it like this then could cause issues:
```
console.log(otherArguments.originalLibraryFile.footprintId)
console.log(otherArguments.originalLibraryFile.file)
```

As the console have the logs seemingly out of order as the workers are running in parallel. So it might output:
```
worker1:console.log(otherArguments.originalLibraryFile.footprintId)
worker2:console.log(otherArguments.originalLibraryFile.footprintId)
worker1:console.log(otherArguments.originalLibraryFile.file)
worker2:console.log(otherArguments.originalLibraryFile.file)
```

So reading that might be misleading as given how the code was written you might expect line 3 and line2 to be from the same worker.

**Comment by UnknownWitcher** [comment]
I replicated it there now using the following code in 3 of my plugins that use CPU with 3 different files.

```
response.infoLog += `${otherArguments.originalLibraryFile.footprintId} - ${otherArguments.originalLibraryFile.file}`
response.infoLog += JSON.stringify(otherArguments.originalLibraryFile)
return response;
```

Results are identical across all three files with all 3 plugins, now I have CPU setup to process 2 files at a time so this is only occuring 3 times due to me immediatly skipping the plugin instead of processing the 2 files. 

CPU WORKER: 2, HEALTH CHECK: 1, GPU WORKER: 1, HEALTH CHECK: 0

```
nCd78ROfv - /data/local/origin/Films/media/Smallville (2001) - S01E01 - Pilot [AVC Bluray-1080p Remux][8bit][AVC][DTS-HD MA 5.1]-FraMeSToR.mkv
{
    "_id": "/data/local/origin/Films/media/Smallville (2001) - S01E01 - Pilot [AVC Bluray-1080p Remux][8bit][AVC][DTS-HD MA 5.1]-FraMeSToR.mkv",
    "footprintId": "nCd78ROfv",
    "file": "/data/local/origin/Films/media/Smallville (2001) - S01E01 - Pilot [AVC Bluray-1080p Remux][8bit][AVC][DTS-HD MA 5.1]-FraMeSToR.mkv",
    "container": "mkv",
------------------------------------------------------
nCd78ROfv - /data/local/origin/Films/media/Ace Ventura When Nature Calls (1995) {imdb-tt0112281} [Remux-1080p][DTS-HD MA 5.0][AVC]-FraMeSToR.mkv
{
    "_id": "/data/local/origin/Films/media/Ace Ventura When Nature Calls (1995) {imdb-tt0112281} [Remux-1080p][DTS-HD MA 5.0][AVC]-FraMeSToR.mkv",
    "footprintId": "nCd78ROfv",
    "file": "/data/local/origin/Films/media/Ace Ventura When Nature Calls (1995) {imdb-tt0112281} [Remux-1080p][DTS-HD MA 5.0][AVC]-FraMeSToR.mkv",
    "container": "mkv",
------------------------------------------------------
nCd78ROfv - /data/local/origin/Films/media/10 Cloverfield Lane (2016) {imdb-tt1179933} [Remux-1080p][TrueHD Atmos 7.1][AVC]-iFT.mkv
{
    "_id": "/data/local/origin/Films/media/10 Cloverfield Lane (2016) {imdb-tt1179933} [Remux-1080p][TrueHD Atmos 7.1][AVC]-iFT.mkv",
    "footprintId": "nCd78ROfv",
    "file": "/data/local/origin/Films/media/10 Cloverfield Lane (2016) {imdb-tt1179933} [Remux-1080p][TrueHD Atmos 7.1][AVC]-iFT.mkv",
    "container": "mkv",
```

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/82295355/435fae55-58a5-4ac4-96cc-e5293d4fda71)

So I cleared the data from the DB2 folder, restarted tdarr and did it again, this time the files processed 2 at a time instead of skipping and I ended up with two identical footprintId's since two files were processed at the same time with the CPU.

```
Footprint: mxujNCybXQ (based on webui)
mxujNCybXQ - /data/local/origin/Films/media/Ace Ventura When Nature Calls (1995) {imdb-tt0112281} [Remux-1080p][DTS-HD MA 5.0][AVC]-FraMeSToR.mkv

Footprint: 9ryBFeyUVT (based on webui)
mxujNCybXQ - /data/local/origin/Films/media/Smallville (2001) - S01E01 - Pilot [AVC Bluray-1080p Remux][8bit][AVC][DTS-HD MA 5.1]-FraMeSToR.mkv

Footprint: gMKk8T_Fb (based on webui)
gMKk8T_Fb - /data/local/origin/Films/media/10 Cloverfield Lane (2016) {imdb-tt1179933} [Remux-1080p][TrueHD Atmos 7.1][AVC]-iFT.mkv
```

I then grabbed `Tdarr_Plugin_MC93_Migz1FFMPEG` and repeated the whole process, deleting data from DB2, restarting tdarr and running those 3 files again, this time though I skipped processing with this plugin and just added the return response, I also added in one of my own plugins to do the same, this time though I increased the amount of gpu and cpu workers + health checks to make sure that all the files ran at the same time or as close as possible.

CPU WORKER: 4, HEALTH CHECK: 2, GPU WORKER: 4, HEALTH CHECK: 2

```

Footprint: byn7ozYwHl (based on webui)
2023-05-26T10:41:43.148Z Pre-processing - Tdarr_Plugin_MC93_Migz1FFMPEG
2023-05-26T10:41:43.148Z rIJr9HzmP8 - /data/local/origin/Films/media/Smallville (2001) - S01E01 - Pilot [AVC Bluray-1080p Remux][8bit][AVC][DTS-HD MA 5.1]-FraMeSToR.mkv

2023-05-26T10:41:43.148Z Pre-processing - Tdarr_Plugin_02uw_Pre_Remove_Chapters
2023-05-26T10:41:43.148Z rIJr9HzmP8 - /data/local/origin/Films/media/Smallville (2001) - S01E01 - Pilot [AVC Bluray-1080p Remux][8bit][AVC][DTS-HD MA 5.1]-FraMeSToR.mkv{

Footprint: rIJr9HzmP8 (based on webui)
2023-05-26T10:41:43.157Z Pre-processing - Tdarr_Plugin_MC93_Migz1FFMPEG
2023-05-26T10:41:43.157Z rIJr9HzmP8 - /data/local/origin/Films/media/Ace Ventura When Nature Calls (1995) {imdb-tt0112281} [Remux-1080p][DTS-HD MA 5.0][AVC]-FraMeSToR.mkv

2023-05-26T10:41:43.157Z Pre-processing - Tdarr_Plugin_02uw_Pre_Remove_Chapters
2023-05-26T10:41:43.157Z rIJr9HzmP8 - /data/local/origin/Films/media/Ace Ventura When Nature Calls (1995) {imdb-tt0112281} [Remux-1080p][DTS-HD MA 5.0][AVC]-FraMeSToR.mkv

Footprint: Lui8NhuAc (based on webui)
2023-05-26T10:41:44.199Z Pre-processing - Tdarr_Plugin_MC93_Migz1FFMPEG
2023-05-26T10:41:44.199Z Lui8NhuAc - /data/local/origin/Films/media/10 Cloverfield Lane (2016) {imdb-tt1179933} [Remux-1080p][TrueHD Atmos 7.1][AVC]-iFT.mkv

2023-05-26T10:41:44.199Z Pre-processing - Tdarr_Plugin_02uw_Pre_Remove_Chapters
2023-05-26T10:41:44.199Z Lui8NhuAc - /data/local/origin/Films/media/10 Cloverfield Lane (2016) {imdb-tt1179933} [Remux-1080p][TrueHD Atmos 7.1][AVC]-iFT.mkv
```

This time it surprised me, as I was expecting all 3 to show the same footprintId but instead only two files ended up with the same footprintId.

Browser: Firefox 113.0.2 (64-bit) on windows 
Tdarr is running in docker on Ubuntu 22.04.1 LTS (GNU/Linux 5.19.0-35-generic x86_64) with no extra nodes

I decided to run this again but in chrome to see if there would be any difference as I haven't cleared my cache on firefox and I haven't used chrome to perform any of these tasks, and I got the same result as above, 2/3 files had the same footprintId.

Also note that I came across this issue when my files were being processed by my plugins, so skipping the processing to just return infoLog is showing the exact same results that I received when processing my files.

**Comment by UnknownWitcher** [comment]
Not sure why, but updating to version 2.00.21 seems to have fixed this for me.

**Comment by HaveAGitGat** [comment]
Thanks for the update 👌
