### ISSUE TITLE
Tdarr_Plugin_00td_filter_by_file_property configured not actually breaking out when no match

### ISSUE THREAD

**Issue by markfaine** [HaveAGitGat/Tdarr_Plugins#419]
I have Tdarr_Plugin_00td_filter_by_file_property configured to look at the file property for one of two strings and break out if it doesn't find it.

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/949949/71633c79-994b-4ad2-ae7a-96e7d35c4822)

The next plugin in the list is Tdarr_Plugin_z18t_rename_files_based_on_codec_and_resolution

The logs show that it is working, however, the rename plugin still runs.  

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/949949/4d04fcb2-1285-4885-85b1-0ed645160065)

**Comment by HaveAGitGat** [comment]
You can set whether you want it to break or continue if the property is found or not. Set `continueIfPropertyFound` to `false` in the plugin inputs. Hope that helps.
