### ISSUE TITLE
keep_original_date fails to find file when monitor file system events is enabled

### ISSUE THREAD

**Issue by didster** [HaveAGitGat/Tdarr_Plugins#424]
Perhaps I have things setup incorrectly, apologies if so.

Simple setup with server (2.00.21) running under docker and one windows GPU transcode node.

When using the Tdarr_Plugin_z80t_keep_original_date plugin as the last entry in the stack, it fails to update the date/time if the "Folder watch" option is on for the respective library.

This seems to be from the logs because the original item is moved from the library as part of the copy operation and Tdarr picks that up before the date plugin has chance to run and removes it from its DB.  Thus when the date plugin looks for the original file in the library via the API to obtain the old date, its no longer there.

Relevant logs below.

It works fine if you just use background scanning of the folder every X hours

> [2023-06-30T13:13:22.909] [INFO] Tdarr_Server - Aj0iwbBbc3 File scanner exited
**[2023-06-30T13:13:48.771] [INFO] Tdarr_Server - bTpamt5Sd: detected file remove, removing from DB:/media/Foo/Circle_Cut991_x264.mp4**
Waiting 5 seconds...
Fetching file object for /media/Foo/Circle_Cut991_x264.mkv...
[2023-06-30T13:13:57.363] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.mkv
Response for /media/Foo/Circle_Cut991_x264.mkv is empty
**Fetching file object for /media/Foo/Circle_Cut991_x264.mp4...
[2023-06-30T13:13:57.477] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.mp4
Response for /media/Foo/Circle_Cut991_x264.mp4 is empty**
Fetching file object for /media/Foo/Circle_Cut991_x264.mov...
[2023-06-30T13:13:57.591] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.mov
Response for /media/Foo/Circle_Cut991_x264.mov is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.m4v...
[2023-06-30T13:13:57.737] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.m4v
Response for /media/Foo/Circle_Cut991_x264.m4v is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.mpg...
[2023-06-30T13:13:57.814] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.mpg
Response for /media/Foo/Circle_Cut991_x264.mpg is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.mpeg...
[2023-06-30T13:13:57.890] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.mpeg
Response for /media/Foo/Circle_Cut991_x264.mpeg is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.avi...
[2023-06-30T13:13:57.977] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.avi
Response for /media/Foo/Circle_Cut991_x264.avi is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.flv...
[2023-06-30T13:13:58.056] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.flv
Response for /media/Foo/Circle_Cut991_x264.flv is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.webm...
[2023-06-30T13:13:58.131] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.webm
Response for /media/Foo/Circle_Cut991_x264.webm is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.wmv...
[2023-06-30T13:13:58.205] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.wmv
Response for /media/Foo/Circle_Cut991_x264.wmv is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.vob...
[2023-06-30T13:13:58.280] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.vob
Response for /media/Foo/Circle_Cut991_x264.vob is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.evo...
[2023-06-30T13:13:58.354] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.evo
Response for /media/Foo/Circle_Cut991_x264.evo is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.iso...
[2023-06-30T13:13:58.429] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.iso
Response for /media/Foo/Circle_Cut991_x264.iso is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.m2ts...
[2023-06-30T13:13:58.504] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.m2ts
Response for /media/Foo/Circle_Cut991_x264.m2ts is empty
Fetching file object for /media/Foo/Circle_Cut991_x264.ts...
[2023-06-30T13:13:58.582] [INFO] Tdarr_Server - /media/Foo/Circle_Cut991_x264.ts
Response for /media/Foo/Circle_Cut991_x264.ts is empty
Could not get file info from API, giving up.

**Comment by didster** [comment]
If anyone else has this issue - the pair of plugins by grut_gut mentioned [here ](https://www.reddit.com/r/Tdarr/comments/qujawa/possible_to_keep_original_files_create_dates/) from [this](https://github.com/gauth-fr/Tdarr_Plugins) fork work much better.  The dates are saved by a pre-processor to a json file alongside the media and then restored via a post-processor.

**Comment by HaveAGitGat** [comment]
I've updated this plugin so it doesn't need to do network requests but instead uses data already provided to the plugin `otherArguments.originalLibraryFile.statSync.mtimeMs`

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/476/files
