### ISSUE TITLE
Rerun mkvpropedit only after Transcode plugin requests a transcode.

### ISSUE THREAD

**Issue by ArabCoders** [HaveAGitGat/Tdarr_Plugins#433]
Hi,

It would be great to fully enable the option of `Run mkvpropedit on files before running plugins` and have it only re-trigger if a plugin request transcode. It's somewhat pointless to retrigger it for every plugin even if the file object hasn't changed.

**Comment by HaveAGitGat** [comment]
Sure will look into adding this

**Comment by HaveAGitGat** [comment]
Added a way to do this in Tdarr Flows Alpha (released yesterday), so can do this for example:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/87805ebe-c0f6-4ea8-950e-1202c7d290f5)
