### ISSUE TITLE
Flow Plugin request: Rename the output file and move to original folder

### ISSUE THREAD

**Issue by Werve** [HaveAGitGat/Tdarr_Plugins#441]
To facilitate further testing (e.g., a VMAF comparison) it would be useful to have a plugin that does not replace/delete the original video and moves the encoded video (with different name) to the same folder as the original.

Also could be useful a VMAF filter (e.g if the resulting file have less than x VMAF set transcode error or retry the encoding with different ffmpeg values)

**Comment by HaveAGitGat** [comment]
This would probably be done by using a rename plugin then move to original directory plugin

**Comment by Werve** [comment]
Thank you, I will try it soon.
If I understand it correctly, it uses the rename by resolution plugin, so you can't create custom prefixes/suffixes to avoid name conflicts in the same folder.

**Comment by HaveAGitGat** [comment]
No it's a custom rename, click on the plugin input. So here it's set to `${fileName}_480p.${container}`. But you can changed to anything, `${fileName}_test.${container}`, `hello_${fileName}.${container}`, just have to update the others to match.

**Comment by wieluk** [comment]
Can I use {codec} or something like that here?
