### ISSUE TITLE
Flow Error on Check HDR

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr_Plugins#449]
Getting an error when using a flow to execute a normal plugin stack but check for HDR files in the process. 
2023-08-30T21:40:10.018Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:[Step W03] [C3] Running plugin: 1.0.0: checkHdr: Check HDR
2 2023-08-30T21:40:10.018Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Scanning original library file
3 2023-08-30T21:40:10.018Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:{
4 2023-08-30T21:40:10.018Z "exifToolScan": true,
5 2023-08-30T21:40:10.018Z "mediaInfoScan": false,
6 2023-08-30T21:40:10.018Z "closedCaptionScan": false
7 2023-08-30T21:40:10.018Z }
8 2023-08-30T21:40:10.018Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Loading source file: /data/tv/-hidden
9 2023-08-30T21:40:10.018Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Scanning source file: /data/tv/-hidden
10 2023-08-30T21:40:10.018Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Scan types: {
11 2023-08-30T21:40:10.018Z "exifToolScan": true,
12 2023-08-30T21:40:10.018Z "mediaInfoScan": false,
13 2023-08-30T21:40:10.018Z "closedCaptionScan": false
14 2023-08-30T21:40:10.018Z }
15 2023-08-30T21:40:10.019Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Requesting Tdarr Server to scan file
16 2023-08-30T21:40:10.019Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Scan complete
17 2023-08-30T21:40:10.019Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Source file scan complete
18 2023-08-30T21:40:10.019Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:Loaded plugin inputs: {}
19 2023-08-30T21:40:10.019Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:[-error-]
20 2023-08-30T21:40:10.019Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:TypeError: Cannot read properties of undefined (reading 'streams')
21 2023-08-30T21:40:10.020Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:"Cannot read properties of undefined (reading 'streams')"
22 2023-08-30T21:40:10.020Z Z6c2H84MI:Node[MainNode]:Worker[only-okapi]:"TypeError: Cannot read properties of undefined (reading 'streams')\n at Object.plugin (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/video/checkHdr/1.0.0/index.js:34:54)\n at a.<anonymous> (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:11624)\n at k (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:2494)\n at Object.next (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:1583)\n at h (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:1049)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/32966295/ff3c7cf2-65a0-45d9-9e08-69a597568c03)

**Comment by HaveAGitGat** [comment]
Thanks, fixed: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/450

**Comment by clifford64** [comment]
I tested the fix with the flow I have configured above and an HDR enabled file skipped the "Add HDR Audio Track" and went right to "Remove extra Subtitles".

**Comment by clifford64** [comment]
Unless I am missing the part where true is on right and false is on left in flows.

**Comment by HaveAGitGat** [comment]
Thanks I’ll clarify it but that plug-in is checking HDR video not audio hence it’s in the video section.

**Comment by clifford64** [comment]
> Thanks I’ll clarify it but that plug-in is checking HDR video not audio hence it’s in the video section.

That's the issue, the file in my flow is HDR, but it is not being detected as HDR. I think this is because it is using the wrong check with FFProbe data. It is checking the Video stream for a "&& stream.transfer_characteristics === 'smpte2084'" but my FFProbe data doesn't show this as a file attribute. I see "stream.color_transfer = smpte2084" when it comes to HDR files. Because this doesn't match the HDR check, it will effectively see all HDR files as not HDR.
