### ISSUE TITLE
Check Video Resolution flow plugin not working

### ISSUE THREAD

**Issue by Technomancer-2048** [HaveAGitGat/Tdarr_Plugins#453]
The plugin always selects output 1 regardless of the input file resolution

**Comment by HaveAGitGat** [comment]
Woops thought I'd done that one already. Fixed here thanks: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/454/files

Click update plugins on the community plugins tab to force an update on the server. Restarting the node will cause it to update (or updates automatically hourly)

**Comment by Technomancer-2048** [comment]
Thanks for your quick response, this will be very helpful.
