### ISSUE TITLE
Flow Plugin: Limit FPS

### ISSUE THREAD

**Issue by Schmidsfeld** [HaveAGitGat/Tdarr_Plugins#457]
A Flo welemnt to reduce the FPS if it is over a certain threshold.

Some video files are encoded using 60 or eaven 120fps. Often this is not neccesary to arcive the files and a lot of data can be saved. In raw there would be a 50-75% reduction that tanslates rougly to 20-30% after encoding (less b frames etc.)

Note: 
It is not as simple as setting the framerate in ffmpeg via a "-r 30" or "-vf fps=30" option. These would also increase for example 24fps videos to 30 defeating the purpose...

In theory this node could also be split into two nodes. One determining FPS (similar to the reolution plugin) and one changing the FPS.

**Comment by HaveAGitGat** [comment]
Added the check for this:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/02edfb93-7f15-4960-9e80-6dd58edeb5d7)

Will do the encode option plugin at another time.

**Comment by HaveAGitGat** [comment]
Added here: 

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/479/files#diff-47dc0833d3da6431ce969c8b9261ab50fb4f6ccb4aec63aa08598e07ff186660

Logic seems to be working ok:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/edea3f2a-45dd-449b-bdc0-367f39da4584)

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/b3619c80-74cd-48a7-8d23-247f7156e3f5)
