### ISSUE TITLE
Local Flow Pluginsnot synced to nodes

### ISSUE THREAD

**Issue by cemtaylor** [HaveAGitGat/Tdarr_Plugins#465]
Hi, I realise this feature isn't quite documented yet and understand Flows are marked as beta. 
I found the LocalFlowPlugins directory allows local flow plugins to be created which I've started to use.

The issue I've noticed is that these local plugins aren't synced to nodes like the non-flow local plugins are, so it's a bit of a manual task to copy local flow plugins to each node while developing them.

**Comment by HaveAGitGat** [comment]
Hi, local plugins are read from the server and executed in memory by the nodes so don’t need to have the files copied. Just need to make sure the local plugins don’t require any extra files

**Comment by cemtaylor** [comment]
I don't think the syncing is working at the moment, if I don't manually copy over the LocalFlowPlugins directory to Tdarr_Node/assets/app/plugins/FlowPlugins/LocalFlowPlugins I get errors attempting to load the FlowHelpers modules, I've attached the node log for when it attempts to run the plugin:
[TdarrLog.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/12574337/TdarrLog.txt)

Going off the error there, possibly an issue with resolving the path to the FlowHelpers directory when it's being read from the server?

**Comment by cemtaylor** [comment]
Actually thinking about it a bit more, I believe the issue is here:

[2023-09-11T10:14:56.871] [ERROR] Tdarr_Node - Error: Cannot find module '../../../../FlowHelpers/1.0.0/cliUtils'
Require stack:
- D:/tdarr/Tdarr_Node/assets/app/plugins/FlowPlugins/LocalFlowPlugins/checkForCorruption/1.0.0/index_cPMp9wvx0IC.js

----

Server side plugins are stored in category/plugin_name/version.number.here/index.js - but it seems that the category is not present in the path when it's sent over to the node, which breaks the relative import to FlowHelpers

**Comment by HaveAGitGat** [comment]
Hi sorry was away for a bit. Yeah that's right, for local plugins you'd need to make sure everything needed is in the single js file (or you can import something from the `methods` or `CommunityFlowPlugins` which are the same across all server/nodes as they're downloaded from the GitHub repo). Other option is to set the `Community plugins repository` to your own one on the `Options` tab.

**Comment by Kedryn** [comment]
But i dont have a Local folder for FLOWS plugin.
You do?

**Comment by HaveAGitGat** [comment]
@Kedryn you just create it next to the community one: 
https://github.com/HaveAGitGat/Tdarr_Plugins/issues/471#issuecomment-1729051271

I'll update it so it's auto created

**Comment by cemtaylor** [comment]
> Hi sorry was away for a bit. Yeah that's right, for local plugins you'd need to make sure everything needed is in the single js file (or you can import something from the `methods` or `CommunityFlowPlugins` which are the same across all server/nodes as they're downloaded from the GitHub repo). Other option is to set the `Community plugins repository` to your own one on the `Options` tab.

I think importing from methods will also not work here, the core issue is for local plugins the path isn't resolved correctly if the plugin is being sent from the server (from testing, this only happens when the client does not have a local copy of the plugin already).

I have my local plugin here on server side:
`/app/server/Tdarr/Plugins/FlowPlugins/LocalFlowPlugins/video/checkForCorruption/1.0.0/index.js`

Within this file I have relative import (after compile from ts to js)
`var cliUtils_1 = require("../../../../FlowHelpers/1.0.0/cliUtils");`

Server side this resolves correctly, however when the plugin is attempted to be dynamically loaded on the client, the path does not include the **video** category:
`D:/tdarr/Tdarr_Node/assets/app/plugins/FlowPlugins/LocalFlowPlugins/checkForCorruption/1.0.0/index_cPMp9wvx0IC.js`

This should be:

`D:/tdarr/Tdarr_Node/assets/app/plugins/FlowPlugins/LocalFlowPlugins/video/checkForCorruption/1.0.0/index_cPMp9wvx0IC.js`

So it's looking for a relative import that's now 1 level above where it actually is because it's missing a directory (in this case, the video directory) when being sent to the node (this is the same on linux and windows hosts). I believe if this is fixed it would remove the need to manually create & share out a LocalFlowPlugins directory and would work like local plugins do in the Plugin Stack environment

**Comment by HaveAGitGat** [comment]
@cemtaylor which Tdarr version are you on?I've just tried with that and seems to be working fine. I added this to the top of the local flow plugin:

```
var cliUtils_1 = require("../../../../FlowHelpers/1.0.0/cliUtils");
console.log(cliUtils_1);
```

Refreshing the flows tab causes the plugin to reload so this shows in the console:

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/6a080c4e-e883-4885-bfa4-9f0142f6705b)

Then when it runs on the node it shows:

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/328cd35c-2610-474b-9611-bc7f73c16c0d)

So seems to be working from what I can see.

**Comment by cemtaylor** [comment]
Hey, server and nodes are running 2.11.01
Example plugin TS code:
https://gist.github.com/cemtaylor/f46b4577de07d0c659acf32a80177c25
Plugin after conversion to js placed on server at /app/server/Tdarr/Plugins/FlowPlugins/LocalFlowPlugins/file/demoPlugin/1.0.0/index.js:
https://gist.github.com/cemtaylor/8824b058daccb63c0cb3ef064eb9da0b

Windows node with plugin not copied across manually:
https://gist.github.com/cemtaylor/21846fb0918d946b6397adb36d44e46a

Windows node with plugin copied across manually to G:/TDARR/Tdarr_Node/assets/app/plugins/FlowPlugins/LocalFlowPlugins/file/demoPlugin/1.0.0/index.js:
https://gist.github.com/cemtaylor/82394e7888eb17db9a5a17a45433459c

Built in Linux node (docker) not copied across manually:
https://gist.github.com/cemtaylor/eca5b7b01937e6c14413093d462235d7

Built in Linux node (docker) copied across manually to /app/Tdarr_Node/assets/app/plugins/FlowPlugins/LocalFlowPlugins/file/demoPlugin/1.0.0/index.js:
https://gist.github.com/cemtaylor/74074f4bf6337292496abd31c282f2e2

**Comment by HaveAGitGat** [comment]
Thanks for the info. Issue is that you need to create the local plugin folder structure on the node. The index.js file can be empty. I've added a small fix so you don't need to do this on the next version.

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/264a447e-bfdc-4760-a16d-5e11ceb7b9a5)


I'll update the plugins system so the nodes just download the plugins from the server so that everything is more in sync and you can more simply require files in your local plugins.

**Comment by cemtaylor** [comment]
That's great, thanks a lot!

**Comment by HaveAGitGat** [comment]
No problem :), 2.12.01 released
