### ISSUE TITLE
FLOWS: New file duration  check

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr_Plugins#467]
I would like the Tdarr_Plugin_a9he_New_file_size_check ported to FLOWS, with conditional percentage for < = >

**Comment by HaveAGitGat** [comment]
Added `Compare File Size Ratio` https://github.com/HaveAGitGat/Tdarr_Plugins/pull/473

**Comment by Kedryn** [comment]
I made a mistake, 
i wrote 2 request, one for file size with percent, and one with file duration (this one) also with precentage.
But i mentioned the size classic plugin instead of the duration one.

I'll close the other ticket and open a new one with the file duration
