### ISSUE TITLE
Local folder for flows

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr_Plugins#471]
The first plugin we need, is not a plugin, but the "Local" folder for Flows like for Legacy plugins. I wrote a flow plugin for myself and put in the community folder, but i can't use it because it keeps getting deleted by Tdarr

**Comment by HaveAGitGat** [comment]
Should work if you put it in the `LocalFlowPlugins` folder:

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/2395b07a-0f55-42c7-86fc-4dcdddc52844)

**Comment by HaveAGitGat** [comment]
Likewise for templates
