### ISSUE TITLE
Flows: expand REVIEW

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr_Plugins#482]
Right now, with the plugin review, we can only accept (review) or requeue
It would be useful to expand  it to at least a "Review/Skip/Requeue" or, a "Proceed/Fail/Requeue"

For example, right now i have a movie that was 12GB, compressed to 2, that is outside the size change usually accepted for my transcode, but that difference, in this case, is legit because the original file had too much high bitrate and was 4K (i don't have a 4k monitor).
But, as is, i can only requeue (and it go back to same encoded size after a while) or Review, that in my flow menas that the new file is discarded and the original restored.

a Third option would allow me to have a third flow that accept the new size and replace original.

**Comment by HaveAGitGat** [comment]
This is already open here thanks: https://github.com/HaveAGitGat/Tdarr/issues/862#issuecomment-1741829183
