### ISSUE TITLE
10 Bit check (flow plugin)

### ISSUE THREAD

**Issue by Technomancer-2048** [HaveAGitGat/Tdarr_Plugins#483]
The 10-bit check seems to default to output 2 ( not 10-bit), I have tried adding a Run MKVPropEdit to correct the details before processing the 10-bit check, but I still get the same result.

**Comment by Technomancer-2048** [comment]
Output from ffprobe:
"file_size":5274.523817062378
"ffProbeData":{
"streams":[
0:{
"index":0
"codec_name":"hevc"
"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)"
"profile":"Main 10"
"codec_type":"video"
"codec_tag_string":"[0][0][0][0]"
"codec_tag":"0x0000"
"width":1920
"height":800
"coded_width":1920
"coded_height":800
"closed_captions":0
"has_b_frames":2
"sample_aspect_ratio":"1:1"
"display_aspect_ratio":"12:5"
"pix_fmt":"yuv420p10le"
"level":120
"color_range":"tv"
"chroma_location":"left"
"refs":1
"r_frame_rate":"24000/1001"
"avg_frame_rate":"24000/1001"
"time_base":"1/1000"
"start_pts":0
"start_time":"0.000000"
"disposition":{
"default":1
"dub":0
"original":0
"comment":0
"lyrics":0
"karaoke":0
"forced":0
"hearing_impaired":0
"visual_impaired":0
"clean_effects":0
"attached_pic":0
"timed_thumbnails":0
"captions":0
"descriptions":0
"metadata":0
"dependent":0
"still_image":0
}
"tags":{
"BPS-eng":"5459543"
"DURATION-eng":"02:01:02.297000000"
"NUMBER_OF_FRAMES-eng":"174121"
"NUMBER_OF_BYTES-eng":"4956103442"
"_STATISTICS_WRITING_APP-eng":"mkvmerge v32.0.0 ('Astral Progressions') 64-bit"
"_STATISTICS_WRITING_DATE_UTC-eng":"2019-07-23 03:28:31"
"_STATISTICS_TAGS-eng":"BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
}
}

**Comment by HaveAGitGat** [comment]
Plugin was just checking `bits_per_raw_sample === 10` but added an additional check here thanks:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/486/files
