### ISSUE TITLE
How to generate  "Example file object"

### ISSUE THREAD

**Issue by luigi311** [HaveAGitGat/Tdarr_Plugins#5]
I am trying to make something but i am having trouble trying to locate a tag. How do you generate the example file object that you have on the readme?  Is there a way to generate that exact output via linux terminal? Can you put that information on the wiki?

**Comment by luigi311** [comment]
A not so nice way to generate it is to make the plugin output it to the info.
 var jsonString = JSON.stringify(file)
response.infoLog += `${jsonString}`

**Comment by HaveAGitGat** [comment]
@luigi311 
If you press the ‘i’ (info) button when you search for a file then that contains the file object although not in exactly the same formatting.  

I’ll have a look at a different way for formatting.

**Comment by HaveAGitGat** [comment]
1.009 will have a formatted file object when you press the 'i' button in the search results.

**Comment by HaveAGitGat** [comment]
1.101 released:
![image](https://user-images.githubusercontent.com/43864057/70356702-e2461600-186c-11ea-8a49-6a37531f244c.png)
