### ISSUE TITLE
Flows option to check audio codec

### ISSUE THREAD

**Issue by sinofsociety** [HaveAGitGat/Tdarr_Plugins#516]
I'd like Tdarr's Flows to have the option of checking for an audio codec so I can standardize audio streams only when necessary

**Comment by DarkShadowxx** [comment]
I would also appreciate that.

You should also be able to check the audio bitrate.

For example, EAC3 audio may be as low as 256 kbps or as high as 1024 kbps. It should be possible to apply different options to such cases, depending on bitrate and codec.

**Comment by HaveAGitGat** [comment]
@sinofsociety fyi the standardize audio plugin checks if anything needs to be changed already so if all codecs are already in target codec then it won't do anything

**Comment by DarkShadowxx** [comment]
Awesome, thank you.
Could you also add the bitrate option?

**Comment by HaveAGitGat** [comment]
Added:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/97664b57-5c09-48d4-ac04-d3132d6fca06)

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/560
