### ISSUE TITLE
Pluginn still not available "Ensure Audio Stream"

### ISSUE THREAD

**Issue by Schmidsfeld** [HaveAGitGat/Tdarr_Plugins#524]
The "Ensure Audio Stream" Plugin is currently not yet available (acually since a long time). Next to the video Encode ensuring a wanted audio stream (Codec, Channels, Bitrate and Language) is one of the most important tasks of Tdarr for many (if not most) users. 
This is IMHO one of the lync ins to get flows a wider adaption within the user comunity. 

Combine it with the ability to get rit of not wanted Audio streams (that consume unneccesary data) and it would be a great first implementation of a full transcode stack.

**Comment by HaveAGitGat** [comment]
Hi thanks for opening an issue.

You can just the the classic plugin `Tdarr_Plugin_00td_action_add_audio_stream_codec` in a flow or plugin stack, does the exact same thing as what this would do, hence not a priority at the moment and does not really have an effect on usage. I have removed the placeholder for now as I have a few other things which are a higher priority, not sure what your experience is but if you're familiar with typescript then feel free to add the plugin here: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/3a92a8ad32f5294ef44fb7fb86a3af9f23e26e77/FlowPluginsTs/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandEnsureAudioStream/1.0.0/index.ts

So yeah just use  `Tdarr_Plugin_00td_action_add_audio_stream_codec` which does the same thing, hope that helps.

**Comment by HaveAGitGat** [comment]
Added this here:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/528

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/aa8e9032-89f9-4560-a0b9-6705b6c68661)

**Comment by Schmidsfeld** [comment]
Thank you so much! 
I will give it another try in the next release and prep some documentation. If it is as good as it looks so far it is a game changer in usability.

**Comment by HaveAGitGat** [comment]
No problemo :)
