### ISSUE TITLE
Using Set Video Encoder in flow always uses software encoding

### ISSUE THREAD

**Issue by georgemcc** [HaveAGitGat/Tdarr_Plugins#527]
Summary:
I have 2 nodes, both using Intel QSV on Windows.  Using the old plugin stack, or importing the old stack into a flow, works fine.  Hardware encoding to HEVC using QSV works great.  However, using the Set Video Encoder ffmpeg command in a new flow results in the ffmpeg command using the libx265 library always.

Steps:
Using Tdarr 2.14.02
create Basic HEVC Flow,
set the following options for Set Video Encoder
- outputCodec = hevc
- ffmpegPreset =  fast
- ffmpegQuality = 25
- hardwareEndoding = true
- hardwareType = qsv
- hardwareDeciding = true
- forceEncoding = true
switch library to use that flow
send movie to monitored library
observe Tdarr web interface as well as node Task Manager

Result:
display shows node is transcoding using CPU, not GPU. Task Manager on node shows GPU is not in use.   Cancelling and looking at  log shows ffmpeg command using libx265 rather than hardware encoding.

Expect:
note to use  -c:v:0 hevc_qsv -load_plugin hevc_hw for ffmpeg command as the old plugin stack uses

Note:
I've attached the associated job log for reference.  Let me know if I'm missing something.
[IRdk0f5jn-log.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/13260710/IRdk0f5jn-log.txt)

**Comment by greggameplayer** [comment]
i have exactly the same problem on a linux node (docker container on Qnap NAS)

**Comment by HaveAGitGat** [comment]
Please see here thanks:
https://github.com/HaveAGitGat/Tdarr_Plugins/issues/538#issuecomment-1826752515

**Comment by georgemcc** [comment]
@HaveAGitGat  From what I can see of the changes for issue 538, args.workerType always comes back as false for GPU even though there are 2 GPU threads per node in my setup.  So however args.workerType is calculated or when the worker process is launched it's as a CPU worker, not a GPU worker.  I haven't looked much further as I'm unfamiliar with the code base.

**Comment by HaveAGitGat** [comment]
`2023-11-05T12:03:54.045Z IRdk0f5jn:Node[NUC2]:Worker[curly-clam]:{"workerType":"transcodecpu"}`

From the logs you are still using a transcodecpu worker. You need to use a transcodegpu worker

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/a6a879c9-2b01-401b-a9b0-7afc8a5d02f0)


Please post new job report if you've tried with a gpu worker. Tried and working fine on windows and linux for me.

**Comment by greggameplayer** [comment]
here is a capture : 
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/33609333/493f9ca7-9085-4283-ab5a-1127bf480b7a)

**Comment by greggameplayer** [comment]
@HaveAGitGat before using the plugin stack there were absolutely no problem with that

**Comment by georgemcc** [comment]
On another note, aren't flows suppose to run on a single node as opposed to the plugin stack which will wait for a CPU/GPU worker then wait to assign the task to the appropriate node?

If so, then what about the instance where you have an existing HEVC file where you want the subtitles removed or audio transcoded to AC3?  Those are CPU type commands for ffmpeg and would not have a CPU worker available to them, this fail?  Would you have to configure the GPU to do CPU tasks in node options?

**Comment by HaveAGitGat** [comment]
>before using the plugin stack there were absolutely no problem with that

That's because the plugins in the plugin stack are independent of each other so it's possible for a CPU/GPU worker to look through the plugin stack and see if there are any plugins that it can do. Flows on the other hand are executed by a worker in one go.

So both CPU/GPU workers will execute the same flow but you can add different routes in the flow depending on if it's a CPU/GPU worker. The `Set Video Encoder` has logic inside that does this automatically if the `auto` option is set, so it will give CPU transcode args to CPU workers and GPU transcode args to GPU workers.

And the GPU worker will do any CPU related stuff (remux/audio) without any extra configuration, as mentioned whole flow is executed by a single worker.

In terms of the h264 arguments, you can see the ones used to test if the encoder is available here:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/hardwareUtils.ts#L272

So I assume we need to add `-hwaccel_output_format qsv -init_hw_device qsv:hw_any,child_device_type=d3d11va` if it's running on windows but interestingly it works on my windows machine without that.

**Comment by georgemcc** [comment]
Okay…I guess people who have GPU dedicated boxes expect that would be the default worker process rather than CPU.  It looks like the Basic HEVC Flow uses CPU first…not ideal.

Transcode Queue says GPU process:
***@***.***

However it’s using the CPU command line:
[A screenshot of a computer program  Description automatically generated]

--
Thanks,

George

From: HaveAGitGat ***@***.***>
Date: Monday, November 27, 2023 at 10:15 PM
To: HaveAGitGat/Tdarr_Plugins ***@***.***>
Cc: George McCarroll ***@***.***>, Comment ***@***.***>
Subject: Re: [HaveAGitGat/Tdarr_Plugins] Using Set Video Encoder in flow always uses software encoding (Issue #527)

before using the plugin stack there were absolutely no problem with that

That's because the plugins in the plugin stack are independent of each other so it's possible for a CPU/GPU worker to look through the plugin stack and see if there are any plugins that it can do. Flows on the other hand are executed by a worker in one go.

So both CPU/GPU workers will execute the same flow but you can add different routes in the flow depending on if it's a CPU/GPU worker. The Set Video Encoder has logic inside that does this automatically if the auto option is set, so it will give CPU transcode args to CPU workers and GPU transcode args to GPU workers.

And the GPU worker will do any CPU related stuff (remux/audio) without any extra configuration, as mentioned whole flow is executed by a single worker.

In terms of the h264 arguments, you can see the ones used to test if the encoder is available here:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/hardwareUtils.ts#L272

So I assume we need to add -hwaccel_output_format qsv -init_hw_device qsv:hw_any,child_device_type=d3d11va if it's running on windows but interestingly it works on my windows machine without that.

**Comment by HaveAGitGat** [comment]
This is the basic hevc flow, it does not use CPU first:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/39938247-0840-4baf-b7a6-0a63d2decfba)
