### ISSUE TITLE
[Tdarr_Plugin_00td_action_add_audio_stream_codec] TrueHD audio codec doesn't work

### ISSUE THREAD

**Issue by greggameplayer** [HaveAGitGat/Tdarr_Plugins#537]
despite TrueHD audio codec being selectable, it doesn't work because the argument "-strict -2" is needed.

Can you please take that in to consideration inside the plugin ?

**Comment by HaveAGitGat** [comment]
Added ty:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/553
