### ISSUE TITLE
Flows HEVC QSV doesn't work

### ISSUE THREAD

**Issue by greggameplayer** [HaveAGitGat/Tdarr_Plugins#538]
Hello,

when using QSV hardware accelerator in Flows for HEVC, it doesn't work because it uses libx265 in the ffmpeg command instead of hevc_qsv

Can you fix this issue please ?

**Comment by HaveAGitGat** [comment]
You can force this with this option:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/5c9a6eec-57c8-45d0-8d77-8f426daacbd0)

QSV detection is a bit tricky as the auto detection is working for me but I think it's with 10th gen that it's not working. You can see the test command it's trying to run here:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/hardwareUtils.ts#L212

So on my devices that completes successfully but seems is failing on yours.

**Comment by greggameplayer** [comment]
Hello @HaveAGitGat,
Even with that, it doesn't work like you can see, it uses libx265 in the command : 
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/33609333/ffff711d-5546-41f7-b88d-6158781313ac)

**Comment by greggameplayer** [comment]
here is a capture of the log of the plugin, if needed : 
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/33609333/cbb62246-21bf-4386-b2ee-aebc2dce5173)

**Comment by HaveAGitGat** [comment]
Hi assume this is because you are running this on a CPU worker (can't see the top of the logs so can't verify this). QSV uses the iGPU so needs to be run on a GPU worker. 

I'll add some more logging so can see this reasoning in the logs in future.

**Comment by HaveAGitGat** [comment]
Added here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/552/files#diff-2417789d5b16dda9d7a5773d39db449611e71d3a73cf431085a050651130a2f5

**Comment by greggameplayer** [comment]
But even on two separate flows or just by executing ffmpeg actions in the flow it doesn't want to use qsv

**Comment by HaveAGitGat** [comment]
Post job report if possible thanks

**Comment by HaveAGitGat** [comment]
```
023-11-26T19:16:26.342Z Hq-WkLDQs:Node[MyInternalNode]:Worker[jagged-jay]:{"workerType":"transcodecpu"}
```

From the logs you are still using a `transcodecpu` worker. You need to use a `transcodegpu` worker


![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/425227bc-f5b6-4695-9fb8-6ac480b2acea)

**Comment by UnknownWitcher** [comment]
> ```
> 023-11-26T19:16:26.342Z Hq-WkLDQs:Node[MyInternalNode]:Worker[jagged-jay]:{"workerType":"transcodecpu"}
> ```
> 
> From the logs you are still using a `transcodecpu` worker. You need to use a `transcodegpu` worker
> 
> ![image](https://private-user-images.githubusercontent.com/43864057/285726949-425227bc-f5b6-4695-9fb8-6ac480b2acea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjYxMDgsIm5iZiI6MTcwMzYyNTgwOCwicGF0aCI6Ii80Mzg2NDA1Ny8yODU3MjY5NDktNDI1MjI3YmMtZjViNi00Njk1LTlmYjgtNmFjNDgwYjJhY2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNDczNDE3OWFiZTJhYjhiYzhiZWNhYjBkNjEyYmI4ZmQ0NDExNDYzYjY0MDNmZjdiOWU4YmUzZjM0YzQwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XzAWhigG6mO8Ob4tn60X156INCXw6rucp9ZY1Gnuq8g)

Even with the QSV set, once all the GPU workers are in use it will start using the CPU..

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/82295355/1e81ca7a-1468-417f-8edf-50b46102c7ac)

**Comment by samssausages** [comment]
> Even with the QSV set, once all the GPU workers are in use it will start using the CPU..

I'm having the same problem with NVEC.  Unless I put CPU to 0 it will not use the GPU.
Manually set to NVEC.

Works fine for classic plugins.

**Comment by Shigawire** [comment]
Had the same issue. If you force your node to only run GPU jobs, the flows work.
