### ISSUE TITLE
Flow plugin request: delete (empty) folder

### ISSUE THREAD

**Issue by moostmartijn** [HaveAGitGat/Tdarr_Plugins#566]
I would like to request a plugin which is capable of deleting a folder.

I move the final file to another directory, which works fine, but I'm left with an empty original directory. It would be nice to have this directory deleted so you don't have to delete it manually.

**Comment by HaveAGitGat** [comment]
Added here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/568/files#diff-85208021c4eaf1e8066b2430299a20b35dc8f11b935e8c47a861b4a96caeac3e

**Comment by moostmartijn** [comment]
Thanks alot! Works like a charm, it cleans up all the folders, so no manual actions anymore.

**Comment by HaveAGitGat** [comment]
Great :)
