### ISSUE TITLE
NotifyRadarrOrSonarr Flow Plugin has Filename issue

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr_Plugins#578]
I am having failures on the flow step for Notifying Radarr or Sonarr about a file being updated. Both work properly for the majority of files, but I have run into an issue with Sonarr failing to update when the filename has certain special character in the title. For example "...!"

**Comment by yodog** [comment]
im having problems with this plugin as well, except mine is only when the NotifyRadarrOrSonarr is after replaceOriginalFile.

for some reason when replaceOriginalFile does *not* replace the file, NotifyRadarrOrSonarr causes a flow error 

```
TypeError: Cannot read properties of undefined (reading 'movieFile')
```
