### ISSUE TITLE
Add back the original GR34 plugins

### ISSUE THREAD

**Issue by journeym** [HaveAGitGat/Tdarr_Plugins#605]
https://github.com/gauth-fr/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_GR34_GrutSaveOriginalDates.js
https://github.com/gauth-fr/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_GR34_GrutRestoreOriginalDates.js

**Comment by supersnellehenk** [comment]
I don't think these have ever been in the Tdarr repo, so they'd have to be integrated by a PR. Preferably by gauth-fr, the person that made them.

To keep the original date, this should suffice I think. https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_z80t_keep_original_date.js
This plugin can also be ran in a flow using this block: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.ts
