### ISSUE TITLE
Wait for GPU worker plugin

### ISSUE THREAD

**Issue by bsasealteam6** [HaveAGitGat/Tdarr_Plugins#611]
My setup has two separate servers, one that handles CPU work and one that handles GPU work, with each of them being much better and it's respective job than the other.  Can we add a flow option to "Wait for GPU worker" and "Wait for CPU Worker" so I don't have transcoding happening on my CPU node and causing it to be unusable for anything else?

**Comment by tws101** [comment]
So I did try to make this exact plugin for myself, was going to base it off of hold for review.....

However 

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/21160306/f4cd3f7f-bedb-4b28-9d76-bd50893d103d)

hold for review does literally nothing (based on the code above)...  I suspect the back end code in tdarr itself just sees the hold for review plugin and triggers the actually hold for review...

This is not something that can, as of yet, be written into a plugin but it is a much needed tool for flows

**Comment by HaveAGitGat** [comment]
Will be possible in next version, can try dev version here: https://github.com/HaveAGitGat/Tdarr/issues/748#issuecomment-2146710875
