### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jimserio** [HaveAGitGat/Tdarr_Plugins#63]
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/6a21944b4a5b10de2b10ce9f175b30a57c264ba5/Community/Tdarr_Plugin_MC93_Migz5ConvertAudio.js#L87

`Audio track is 8 channel, no 6 channel exists. Creating 2 channel from 6 channel.`

Should be `Creating 2 channel from **8** channel.`?

**Comment by Migz93** [comment]
Hi jimserio,

Correct, thanks for pointing that out. I'll get it fixed with the next PR i do

**Comment by HaveAGitGat** [comment]
Fixed
