### ISSUE TITLE
Flow rename plugin doesn't seem to rename files

### ISSUE THREAD

**Issue by begunfx** [HaveAGitGat/Tdarr_Plugins#646]
I have a rename node in my flow that should append 1080p to the end (this is after a conditional if the size is bigger than 1080p to resize the file then rename it). 

The file gets resized and moved to the proper folder.  so I know it's moving through the flow as expected.

Attached is my flow and the job report.

Flow Export:
[Clean Resize ReTranscode v06.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/15393161/Clean.Resize.ReTranscode.v06.txt)

Job Report:
[5MG6ciwtjL7-log.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/15393162/5MG6ciwtjL7-log.txt)

Running tdarr via Docker on a Synology server running latest DSM 7.2

Thanks in advance for your help.

**Comment by begunfx** [comment]
Thanks for the response @HaveAGitGat.  My expectations and understanding on how the flow works is when the file is resized/processed etc.  its in the cache folder and then when it's completed it will be physically moved into the output folder I specified in my flow.  Before the move the rename should physically rename the file so the file I see in the output folder should have the 1080p appended at the end of the filename.  Currently, I'm seeing the file name stay the same after being processed and moved to the output folder as the original file.  I'm not sure what you mean by "in the Tdarr DB".  Perhaps I'm not understanding how the flow is supposed to work, but that is what I thought is supposed to happen.  

Please try running my flow on the test file: sample__2160__libx264__ac3__30s__video.mkv (located in the tdarr samples page).  I'm seeing this mis-match of expectations on this file.

If my expectations are incorrect, I would appreciate some further clarification on how the rename should work.

Thanks and great job on this tool!

**Comment by begunfx** [comment]
@HaveAGitGat.  Just following up...Any update on this?   Thanks!

**Comment by HaveAGitGat** [comment]
From the log the rename has occurred on disk:

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/def9e71c-87ee-4fba-9d10-23461e6692bc)

Please confirm with a screenshot where you are seeing the original file name. Note in explorer or other file browsers you may need to refresh or reload the window for the new filename to show.

**Comment by begunfx** [comment]
I can confirm via my Synology DSM that the file was not renamed.  See attached (source and output) files.  I'm viewing these within my Synology server's file viewer so caching is not a possibility.  Additionally I removed the files and tried again to make sure I didn't miss anything...still the same.
![resizeSourceTest](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/3505946/d08d67dd-6563-4b3f-9f11-36b5242aea00)
![resizeOutputTest](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/3505946/da6c7e0b-e388-42b4-9566-832b2486fec8)

**Comment by HaveAGitGat** [comment]
@begunfx thanks, seems the rename plugin is actually renaming the file (if you add a 'Require Review' flow plugin after the rename you should be able to see the renamed cache file). It's the Move to Directory file which is causing the issue. Will investigate ty.

**Comment by begunfx** [comment]
Awesome.  Thanks!  Glad you found the issue and were able to fix it. I'll test again when the fix is pushed out.

**Comment by HaveAGitGat** [comment]
It’s already been pushed out 👌.

**Comment by begunfx** [comment]
Sweet.  I'll give it a try.

**Comment by begunfx** [comment]
Just tested and it works!  👍

**Comment by HaveAGitGat** [comment]
Great thanks for the update 🙂
