### ISSUE TITLE
"Require GPU worker" flow equivalent?

### ISSUE THREAD

**Issue by javierlopeza** [HaveAGitGat/Tdarr_Plugins#649]
When using plugins stack the staging section showed "Waiting for GPU worker" when a plugin required such. How can I have a similar behavior now that I switched to Flows? Thanks!

**Comment by HaveAGitGat** [comment]
Answered your other post here:
https://github.com/HaveAGitGat/Tdarr/issues/1009

**Comment by HaveAGitGat** [comment]
2.20.01 released. Example flow with `Tags: Worker Type` :

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/24e98728-4728-4d64-958b-9bb097156ce8)
