### ISSUE TITLE
QSV issue 

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr_Plugins#651]
Since i updated Tdarr&Plugins, now i'm getting this error on all transcodings on my QSV enabled node

33 2024-05-31T12:49:50.441Z Input #0, matroska,webm, from '//172.16.0.190/transcoding_temp/anime_ita/tdarr-workDir-node-0mV-tq6WO-worker-khaki-kagu-ts-1717152563858/1717152568955/TutorHitmanReborn_Ep_103_ITA.mkv':
34 2024-05-31T12:49:50.441Z Metadata:
35 2024-05-31T12:49:50.441Z title : La prima barriera
36 2024-05-31T12:49:50.441Z COMMENT : Tsuna e i suoi amici dovranno scontrarsi con Dendro per poi dirigersi all’ottavo piano. Giannini cerca di ritrovare le comunicazioni con i ragazzi.
37 2024-05-31T12:49:50.441Z MAJOR_BRAND : isom
38 2024-05-31T12:49:50.441Z MINOR_VERSION : 512
39 2024-05-31T12:49:50.441Z COMPATIBLE_BRANDS: isomiso2avc1mp41
40 2024-05-31T12:49:50.441Z ENCODER : Lavf59.16.100
41 2024-05-31T12:49:50.441Z Duration: 00:23:22.01, start: 0.000000, bitrate: 1820 kb/s
42 2024-05-31T12:49:50.441Z Stream #0:0: Video: h264 (High), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
43 2024-05-31T12:49:50.441Z Metadata:
44 2024-05-31T12:49:50.441Z HANDLER_NAME : VideoHandler
45 2024-05-31T12:49:50.441Z VENDOR_ID : [0][0][0][0]
46 2024-05-31T12:49:50.441Z DURATION : 00:23:22.005000000
47 2024-05-31T12:49:50.441Z Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
48 2024-05-31T12:49:50.441Z Metadata:
49 2024-05-31T12:49:50.441Z HANDLER_NAME : SoundHandler
50 2024-05-31T12:49:50.441Z VENDOR_ID : [0][0][0][0]
51 2024-05-31T12:49:50.441Z DURATION : 00:23:21.962000000
52 2024-05-31T12:49:50.441Z WARNING: defaulting child_device_type to AV_HWDEVICE_TYPE_DXVA2 for compatibility with old commandlines. This behaviour will be removed in the future. Please explicitly set device type via "-init_hw_device" option.
53 2024-05-31T12:49:50.441Z Stream mapping:
54 2024-05-31T12:49:50.441Z Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_qsv))
55 2024-05-31T12:49:50.441Z Stream #0:1 -> #0:1 (copy)
56 2024-05-31T12:49:50.441Z Press [q] to stop, [?] for help
57 2024-05-31T12:49:50.441Z Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
58 2024-05-31T12:49:50.441Z Error reinitializing filters!
59 2024-05-31T12:49:50.441Z Failed to inject frame into filter network: Function not implemented
60 2024-05-31T12:49:50.441Z Error while processing the decoded data for stream #0:0
61 2024-05-31T12:49:50.441Z Conversion failed!```

**Comment by HaveAGitGat** [comment]
Thanks, are you able to try the `Boosh-Transcode Using QSV GPU & FFMPEG` classic plugin on a file? Can use the `Run Classic Transcode Plugin` to run it in a flow. Will help confirm if it's a driver issues or not ty.

**Comment by Kedryn** [comment]
[1FGMWfzz0-log.txt](https://github.com/user-attachments/files/15581445/1FGMWfzz0-log.txt)

**Comment by Kedryn** [comment]
ok, the previous attempt failed but other files are working with the classic plugin
now i'll try to re-add all parameter i was using with the flow plugin

**Comment by Kedryn** [comment]
it seems to work even with my additional params
so the problem is the flow plugin itself

**Comment by Kedryn** [comment]
[FVtsu0m3mK-log.txt](https://github.com/user-attachments/files/15585132/FVtsu0m3mK-log.txt)
getting this for many files, with many others are transcoding fine

**Comment by HaveAGitGat** [comment]
```
2024-06-05T11:59:44.590Z "infoLog": "==WARNING== Failed to get an accurate video bitrate, falling back to old method to get OVERALL file bitrate of NaNkbps. Bitrate calculations for video encode will likely be inaccurate...\n10 bit encode enabled. Setting Main10 Profile & 10 bit pixel format\nContainer for output selected as mkv.\nEncode variable bitrate settings:\nTarget = NaNk\nMinimum = NaNk\nMaximum = NaNk\nFile Transcoding...\n"
```
Yeah the boosh plugin tries to do some bitrate calculations using video stream bitrate, duration and a few other things. Those aren't always available as the details aren't added to the file metadata by the previous encoder.  In that case the plugin fails.

But thanks for the previous log, I'll fix the Tdarr flow plugin today so should start working for you.

**Comment by HaveAGitGat** [comment]
Well the offending argument is:

`-vf scale_qsv=format=p010le`

Which works fine on Linux but not on Windows. Changing this to `-pix_fmt:v:0 p010le` works fine.

A small change here should fix it:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/98858a2542c776e54c1f1ea49facdde8b79aea33/FlowPluginsTs/CommunityFlowPlugins/ffmpegCommand/ffmpegCommand10BitVideo/1.0.0/index.ts#L40

**Comment by HaveAGitGat** [comment]
Fixed with this change so should start working for you now if you update plugins on the plugins tab:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/659/files#diff-9b24aa5130dc71a8176a72f566a5f34fea1a1889ef496633c5e180acd78fdf65
