### ISSUE TITLE
replaceOriginalFile: TypeError: (0 , fileUtils_1.fileExists) is not a function

### ISSUE THREAD

**Issue by csangani** [HaveAGitGat/Tdarr_Plugins#654]
Tdarr Node Version: 2.19.01
Platform: Windows 11 23H2

I have multiple node workers running Win 11, and they're all reporting the same error in the logs. I have verified that the workers all have write access to the network shares. After the error, the flow ends and I'm left with .tmp files in the destination folder.

> 1
> 
> 2024-06-02T10:07:43.557Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:[Step W03] [C8] [Basic HEVC CPU Video Flow] Running Community plugin: 1.0.0: replaceOriginalFile: Replace Original File
> 
> 2
> 
> 2024-06-02T10:07:43.557Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Scanning original library file
> 
> 3
> 
> 2024-06-02T10:07:43.557Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:{
> 
> 4
> 
> 2024-06-02T10:07:43.557Z "exifToolScan": true,
> 
> 5
> 
> 2024-06-02T10:07:43.557Z "mediaInfoScan": false,
> 
> 6
> 
> 2024-06-02T10:07:43.557Z "closedCaptionScan": false
> 
> 7
> 
> 2024-06-02T10:07:43.557Z }
> 
> 8
> 
> 2024-06-02T10:07:43.557Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Loading source file: Z:/tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832/1717328558765/[file].mkv
> 
> 9
> 
> 2024-06-02T10:07:43.558Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Scanning source file: Z:/tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832/1717328558765/[file].mkv
> 
> 10
> 
> 2024-06-02T10:07:43.558Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Scan types: {
> 
> 11
> 
> 2024-06-02T10:07:43.558Z "exifToolScan": true,
> 
> 12
> 
> 2024-06-02T10:07:43.558Z "mediaInfoScan": false,
> 
> 13
> 
> 2024-06-02T10:07:43.558Z "closedCaptionScan": false
> 
> 14
> 
> 2024-06-02T10:07:43.558Z }
> 
> 15
> 
> 2024-06-02T10:07:43.558Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Using cached scan results
> 
> 16
> 
> 2024-06-02T10:07:43.558Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Loaded plugin inputs: {}
> 
> 17
> 
> 2024-06-02T10:07:43.558Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:File has changed, replacing original file
> 
> 18
> 
> 2024-06-02T10:07:43.558Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:{"currentPath":"Z:/tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832/1717328558765/[file].mkv","newPath":"R:/[folder]/[file].mkv","newPathTmp":"R:/[folder]/[file].mkv.tmp"}
> 
> 19
> 
> 2024-06-02T10:07:45.561Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Calculating cache file size in bytes
> 
> 20
> 
> 2024-06-02T10:07:45.562Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:353351902
> 
> 21
> 
> 2024-06-02T10:07:45.563Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Attempting move from Z:/tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832/1717328558765/[file].mkv to R:/[folder]/[file].mkv.tmp, method 1
> 
> 22
> 
> 2024-06-02T10:07:45.563Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:File move error: {"errno":-4037,"code":"EXDEV","syscall":"rename","path":"Z:\\tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832\\1717328558765\\[file].mkv","dest":"R:\\[folder]\\[file].mkv.tmp"}
> 
> 23
> 
> 2024-06-02T10:07:45.563Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:After move/copy, destination file of size 0 does not match cache file of size 353351902
> 
> 24
> 
> 2024-06-02T10:07:45.563Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Failed to move file, trying copy
> 
> 25
> 
> 2024-06-02T10:07:45.563Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Attempting copy from Z:/tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832/1717328558765/[file].mkv to R:/[folder]/[file].mkv.tmp , method 1
> 
> 26
> 
> 2024-06-02T10:07:50.570Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:After move/copy, destination file of size 353351902 does match cache file of size 353351902
> 
> 27
> 
> 2024-06-02T10:07:50.570Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Deleting source file Z:/tdarr-workDir-node-IKciOxXQZ-worker-grave-gnat-ts-1717328555832/1717328558765/[file].mkv
> 
> 28
> 
> 2024-06-02T10:07:50.570Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:[-error-]
> 
> 29
> 
> 2024-06-02T10:07:50.571Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:TypeError: (0 , fileUtils_1.fileExists) is not a function
> 
> 30
> 
> 2024-06-02T10:07:50.571Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:"(0 , fileUtils_1.fileExists) is not a function"
> 
> 31
> 
> 2024-06-02T10:07:50.571Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:"TypeError: (0 , fileUtils_1.fileExists) is not a function\n at C:\\Users\\micro\\Downloads\\Tdarr_Updater\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\CommunityFlowPlugins\\file\\replaceOriginalFile\\1.0.0\\index.js:109:65\n at step (C:\\Users\\micro\\Downloads\\Tdarr_Updater\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\CommunityFlowPlugins\\file\\replaceOriginalFile\\1.0.0\\index.js:33:23)\n at Object.next (C:\\Users\\micro\\Downloads\\Tdarr_Updater\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\CommunityFlowPlugins\\file\\replaceOriginalFile\\1.0.0\\index.js:14:53)\n at fulfilled (C:\\Users\\micro\\Downloads\\Tdarr_Updater\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\CommunityFlowPlugins\\file\\replaceOriginalFile\\1.0.0\\index.js:5:58)"
> 
> 32
> 
> 2024-06-02T10:07:50.571Z 6ZOObffnL:Node[Arkana]:Worker[grave-gnat]:Flow has failed

**Comment by HaveAGitGat** [comment]
Please try running the plugin update and retry, seems maybe something interrupted it for you:
![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/a323df6a-af86-4690-9e3f-fa6121945b61)

Reopen if needed ty.
