### ISSUE TITLE
FFMPEG: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by begunfx** [HaveAGitGat/Tdarr_Plugins#673]
I'm running a real simple flow to just trim a movie file down to 1 minute long.  I'm getting the following error:

`Unexpected token u in JSON at position 0`

Either by running a custom FFMPEG command:

`Input arguments: -ss 00:10:00 -to 00:11:00`
`Output arguments: -c copy output.mkv`

 or by using a classic plugin that is utilizing Handbrake/FFMPEG to do the same thing.  The error seems to only happen on a particular movie file.  Attached are the two different flows that error as well as the entire log:

[Sample Generator FFMPEG.txt](https://github.com/user-attachments/files/15922545/Sample.Generator.FFMPEG.txt)
[Sample Generator Handbrake.txt](https://github.com/user-attachments/files/15922546/Sample.Generator.Handbrake.txt)
[csNN1JoFj-log.txt](https://github.com/user-attachments/files/15922549/csNN1JoFj-log.txt)

**Comment by HaveAGitGat** [comment]
```
"file_size":0
"scannerReads":{
"ffProbeRead":""FFprobe was unable to extract any data from this …"
"exiftoolRead":"success"
"mediaInfoRead":"success"
"closedCaptionRead":""Unable to run CCExtractor exit code 10""
}
```

Seems the file cannot be read or accessed by the node? Can the node access this path:

`/media/output/clipped/CAPTAIN_AMERICA_THE_FIRST_AVENGER (2011)_clip.mp4`

**Comment by begunfx** [comment]
I can confirm that the path is accessible.  It is 777 permissions and I have run multiple clips through these flows and all were successful, just not the one in question.  I also checked the permissions on the file itself and it is the same as the other "successful" clips.  Not sure why it would be a permissions issue.  If you want I can PM you a link to the file and you can download and test directly.  Thanks!

**Comment by begunfx** [comment]
Strangest thing.  Apparently after I got the update you pushed out tdarr re-ran the flow in question and successfully processed (trimmed) the clip without error.  To be sure, I ran it again and still success!  I tried with both flows and it worked!  Very strange.  I guess until I can reproduce it again, I'll close this topic.  Thanks!
