### ISSUE TITLE
H265 Files fail check

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr_Plugins#7]
I have recently switched from unmanic to tdarr. I have already converted everything I have to H265 and verified it is converted with the mediainfo command. When using this plugin, my files that have been converted fail to be recognized and then try to convert them to H265 again. I think this has something to do with the Video IDs within the file. Any way to fix this? The files in the queue show that the codec is HEVC, but they are still queued for some reason.

**Comment by HaveAGitGat** [comment]
@clifford64  hi which plugin specifically are you using? There are several h265 ones, are you able to post the ID?

And all files when they are first scanned will appear in the transcode queue. It is only when a worker picks them up that they are assessed to see if they should be transcoded or not.

So although your h265 files appear in the queue, they should be marked as Transcode:Not required and moved to the Transcode:Success/Not require tab. 

Test it with some files 👍

**Comment by clifford64** [comment]
Sorry, I thought the issue was for the specific plugin. The one I am using it the Tdarr_Plugin_075a_FFMPEG_HEVC_Generic.js

**Comment by HaveAGitGat** [comment]
@clifford64 ok haven’t heard of any problems with that one.

So just to clarify, are the files already in h265  transcoded again? Or do they just appear in the queue and are then moved straight to the Transcode:Success/Not required queue?

**Comment by clifford64** [comment]
They are files that are placed in the queue to get transcoded again even though they are already H265. When they are in the queue, the codec shows that it is an HEVC file, but still transcodes. Other files in the queue also show the audio codec in the codec column, such as AC3.

**Comment by HaveAGitGat** [comment]
Are you able to show a screenshot of an expanded worker when it’s transcoding the hevc file?

**Comment by clifford64** [comment]
![image](https://user-images.githubusercontent.com/32966295/69835151-5f3e1380-120d-11ea-817a-7b2552ab3f08.png)
![image](https://user-images.githubusercontent.com/32966295/69835171-77ae2e00-120d-11ea-8bbf-8ee995e4dc1b.png)
![image](https://user-images.githubusercontent.com/32966295/69835192-a9bf9000-120d-11ea-83cb-d514b3dfa219.png)

**Comment by clifford64** [comment]
Ah, I am sorry. I see now that in the first screenshot, it skipped the file because it recognized the codec. However, in the last two screenshots, we see that it is an HEVC file, but it detects the codec as AC3, so it thinks it is not HEVC.

**Comment by HaveAGitGat** [comment]
I think like you mentioned the streams aren’t in the right order as the video should be stream 1. Put the re-order streams plugin at the top of your plugin stack and it should solve the problem 👍

**Comment by clifford64** [comment]
That sounds like a great Idea. I will try that and let you know. Thank you so much for your help.
