### ISSUE TITLE
H264 not being recognised as H264

### ISSUE THREAD

**Issue by UnhealthyKraken** [HaveAGitGat/Tdarr_Plugins#70]
Hi, I am having an issue where it is saying all my H264 files are not H264 and wants to trans-code them again. Is this a common issue?

**Comment by Migz93** [comment]
What plugin are you using?

What does the process message say on that transcode?

If you go onto the search tab, search for the file, click the "i" under info, paste to pastebin and link it here.

**Comment by UnhealthyKraken** [comment]
I have a feeling it is my custom plugin I (attempted) to make to exclude H265, 
The plugin to convert to h264 is Tdarr_Plugin_077b_HandBrake_NVENC_264_Configurable

**Comment by HaveAGitGat** [comment]
If you still need help then please re-open and share your custom plugin so I can have a look. Thanks.
