### ISSUE TITLE
Custom FFMPEG Arguments causes duplication of all data streams

### ISSUE THREAD

**Issue by dockerisedDan** [HaveAGitGat/Tdarr_Plugins#725]
I am playing around with creating my own flow using the FFMPEG command builder. I encoded a file using the new Boosh AV1 plugin to generate an FFMPEG command that I know works on the file, ~1.8GB down to ~600MB.

I simply looked in the logs and copied the input commands to the input field and output commands to the output field of the "Custom Arguments" FFMPEG flow plugin and when executing, Tdarr adds a copy of all streams before my arguments, causing a double of all streams (video, audio, subtitle, image etc.) and bloating the file.

Boosh generated command:
`tdarr-ffmpeg -fflags +genpts -hwaccel_output_format qsv -init_hw_device qsv:hw_any,child_device_type=vaapi -c:v h264 -i /input.mkv -map 0 -c:v av1_qsv -b:v 3672k -minrate 2754k -maxrate 4590k -bufsize 9180k -preset slow -async_depth 4 -aq-mode 4 -look_ahead 1 -look_ahead_depth 100 -b_strategy 1 -adaptive_i 1 -adaptive_b 1 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -f matroska -profile:v main -pix_fmt p010le /output.mkv`

FFMPEG "Custom Arguments" Plugin inputs:
`-fflags +genpts -hwaccel_output_format qsv -init_hw_device qsv:hw_any,child_device_type=vaapi -c:v h264`

`-map 0 -c:v av1_qsv -b:v 3672k -minrate 2754k -maxrate 4590k -bufsize 9180k -preset slow -async_depth 4 -aq-mode 4 -look_ahead 1 -look_ahead_depth 100 -b_strategy 1 -adaptive_i 1 -adaptive_b 1 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -f matroska -profile:v main -pix_fmt p010le`

Generated command when above is Executed:
`tdarr-ffmpeg -y -fflags +genpts -hwaccel_output_format qsv -init_hw_device qsv:hw_any,child_device_type=vaapi -c:v h264 -i /input.mkv -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map 0:2 -c:2 copy -map 0:3 -c:3 copy -map 0:4 -c:4 copy -map 0:5 -c:5 copy -map 0:6 -c:6 copy -map 0:7 -c:7 copy -map 0:8 -c:8 copy -map 0:9 -c:9 copy -map 0:10 -c:10 copy -map 0:11 -c:11 copy -map 0:12 -c:12 copy -map 0:13 -c:13 copy -map 0:14 -c:14 copy -map 0:15 -c:15 copy -map 0:16 -c:16 copy -map 0:17 -c:17 copy -map 0:18 -c:18 copy -map 0:19 -c:19 copy -map 0:20 -c:20 copy -map 0:21 -c:21 copy -map 0:22 -c:22 copy -map 0:23 -c:23 copy -map 0:24 -c:24 copy -map 0:25 -c:25 copy -map 0:26 -c:26 copy -map 0:27 -c:27 copy -map 0:28 -c:28 copy -map 0:29 -c:29 copy -map 0:30 -c:30 copy -map 0:31 -c:31 copy -map 0:32 -c:32 copy -map 0:33 -c:33 copy -map 0:34 -c:34 copy -map 0:35 -c:35 copy -map 0:36 -c:36 copy -map 0:37 -c:37 copy -map 0:38 -c:38 copy -map 0:39 -c:39 copy -map 0:40 -c:40 copy -map 0:41 -c:41 copy -map 0:42 -c:42 copy -map 0:43 -c:43 copy -map 0:44 -c:44 copy -map 0:45 -c:45 copy -map 0:46 -c:46 copy -map 0 -c:v av1_qsv -b:v 3672k -minrate 2754k -maxrate 4590k -bufsize 9180k -preset slow -async_depth 4 -aq-mode 4 -look_ahead 1 -look_ahead_depth 100 -b_strategy 1 -adaptive_i 1 -adaptive_b 1 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -f matroska -profile:v main -pix_fmt p010le /output.mkv`

![commands plugin](https://github.com/user-attachments/assets/45b36c42-e8bd-4db7-a7ab-24e886ff4018)
![flow](https://github.com/user-attachments/assets/ae5c85b6-271c-4bca-9fc4-677c717e1769)

**Comment by supersnellehenk** [comment]
Tdarr automatically maps all streams when the `Begin` command is ran. You can simply remove `-map 0` from your custom command.

You can also run the classic plugin in your flow using the `Run classic transcode plugin`, as the Boosh plugins do some calculation based on the file bitrate and such.
