### ISSUE TITLE
bitrateprobe is undefined in Tdarr_Plugin_d5d3_iiDrakeii_FFMPEG_NVENC_Tiered_MKV

### ISSUE THREAD

**Issue by n0rbertg** [HaveAGitGat/Tdarr_Plugins#73]
Hi,

I am playing with Tdarr_Plugin_d5d3_iiDrakeii_FFMPEG_NVENC_Tiered_MKV plugin and during my tests all the files I tested it with returned  bitrateprobe = undefined.

Because of this the plugin defaults to the preset target bitrates which I'd like to avoid. 

I am not a developer  but looks like 

`bitrateprobe = file.ffProbeData.streams[0].bit_rate
`
comes back with an undefined value every time. How could I fix this?

**Comment by HaveAGitGat** [comment]
Not really something you can fix. Sometimes ffprobe doesn't give bitrate. You could try manually calculating the bitrate based on the duration and file size:

`var bitrate = (file.file_size *8*1000000/file.meta.Duration)`

Hoping to use mediainfo soon to help with this.

**Comment by n0rbertg** [comment]
Thank you for the reply. I've considered using this, for example Migz plugins' are using duration as well but a bit differently. Which one would you recommend?

This is from a Migz plugin:

```
// Check if duration info is filled, if so times it by 0.0166667 to get time in minutes. If not filled then get duration of stream 0 and do the same.
  if (typeof file.meta.Duration != "undefined") {
    var duration = file.meta.Duration * 0.0166667;
  } else {
    var duration = file.ffProbeData.streams[0].duration * 0.0166667;
  }

// Work out currentBitrate using "Bitrate = file size / (number of minutes * .0075)" - Used from here https://blog.frame.io/2017/03/06/calculate-video-bitrates/
  var currentBitrate = ~~(file.file_size / (duration * 0.0075));
```

**Comment by Kooramah** [comment]
I know this is closed and a dead thread but am curious if this was ever fixed? To this day, this plugin is still returning NaNkb bitrate unless its an mp4
