### ISSUE TITLE
Plugin Request: A plugin that extracts the subtitle and makes it a srt file

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr_Plugins#80]
Basically I want a plugin that will extract the subtitle(s) from a file and export it as a srt file. Prefereably it would also delete the embedded subtitle, but it isn't absolutely necessary as there are other plugins that can do that

**Comment by HaveAGitGat** [comment]
What type of subtitles do your files have as this isn't possible with all types?

**Comment by theg00s3** [comment]
subrip and ass subtitles

**Comment by drpeppershaker** [comment]
@theg00s3 subrip as in .srt?

**Comment by theg00s3** [comment]
yes

**Comment by drpeppershaker** [comment]
@theg00s3 Tdarr_Plugin_078d_Output_embedded_subs_to_SRT_and_remove.js seems to do everything you're looking for.

**Comment by theg00s3** [comment]
Oh nice! I didn’t see that. Thanks!
