### ISSUE TITLE
Tdarr_Plugin_MC93_Migz1FFMPEG_CPU

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr_Plugins#84]
When running the plugin on certain mkv files, I get the error:
```
x265 [error]: Picture width must be an integer multiple of the specified chroma subsampling
```

It would be useful it the plugin automatically dealt with this with something along the lines of `-vf scale=1280:trunc(outputWidth/aspectRatio/2)*2` so it always scaled it correctly.

**Comment by HaveAGitGat** [comment]
@Migz93  have you had this issue?

**Comment by Migz93** [comment]
I'm afraid I haven't no but I don't use the CPU version, only the GPU version so i assume it must be something specific to the CPU conversion.
@gregoryduckworth if you're able to get onto our discord and provide a sample file then i can test and make amendments where required. I just don't want to randomly put some extra parameters in without being able to test how that functions.

**Comment by bullmoose20** [comment]
Was this ever resolved? I may have just created a new issue that is exactly this as well...but with more details and a link to a stackoverflow solution... I have two files so far that have this issue... but should be pretty easy to replicate... create a file with an odd number of lines and then try to convert it.

**Comment by HaveAGitGat** [comment]
If anyone is still having this issue then please reopen and add a sample file so can implement a fix.
