### ISSUE TITLE
Help With File Rename

### ISSUE THREAD

**Issue by townsmcp** [HaveAGitGat/Tdarr_Plugins#88]
@HaveAGitGat I would like a bit of help with file renaming please.
I have been playing around with the rename plugin and understnd what the following code snippet is doing (if codec is h264 and filename contains 265, change 265 to 264):

```
    if (
      file.ffProbeData.streams[0].codec_name == "h264" &&
      file._id.includes("265")
    ) {
      file._id = file._id.replace("265", "264");
      file.file = file.file.replace("265", "264");
    }
```

Instead of 'replace', is there a command for append? Ive tried changing 'replace' to 'append' but didnt get anywhere.
The reason for this is Radarr/Sonarr doesnt see the file has changed after encoding being as the output transcoded file is the same file name so Sonarr/Radarr dont do a file scan and update the DB to show the new file size. If the filename is changed a scan will take place and update Sonarr/Radarr DB accordingly.

Ive tried searching on the net for FFProbe and appending the file name but everything has failed me so far. I have tried building a new 'replace' section for codec in the file name but ultimate to cover all scenarios I need one for different resolutions of 480, 720, 1080, different codecs MPEG2, h264, h265 etc - it seems a bit sloppy to have multiple sections all calling a replace when there is probably an append so I can add something such as '_tdarr' to the end of the filename which will then make Radarr/Sonarr do a file scan/update

**Comment by HaveAGitGat** [comment]
Hi, please try this new community plugin. It will update the file name with the resolution and codec:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_z18t_rename_files_based_on_codec_and_resolution.js

**Comment by HaveAGitGat** [comment]
If that doesn't work then I can create a plugin which updates the file with a time stamp. That way you'll always have a fresh filename (appending '_tdarr' would only work the first time, or you'd end up with a really long file name e.g. file_tdarr_tdarr_tdarr.mp4)

**Comment by erichter2018** [comment]
I have an associated request.  The original rename files based on codec works great, but I would love one extra functionality.  If the plugin could check if there is an identically named .en.srt file, and rename that one as well, it would be perfect.  Any suggestion on how to accomplish this?

**Comment by HaveAGitGat** [comment]
> I have an associated request. The original rename files based on codec works great, but I would love one extra functionality. If the plugin could check if there is an identically named .en.srt file, and rename that one as well, it would be perfect. Any suggestion on how to accomplish this?

You could do something like this for that:

```
const fs = require('fs');

const filename = file.originalLibraryFile.file
let parts = filename.split('.')
parts[parts.length - 1] = ['en.srt'];
const srt = parts.join('.');

if (fs.existsSync(srt)) {
    console.log('SRT exists!')
    console.log('Rename...')
}
```
