### ISSUE TITLE
Audio/Subtitle Default track

### ISSUE THREAD

**Issue by Nonobis** [HaveAGitGat/Tdarr_Plugins#9]
Hello,

How to make a plugin to set default track ?

Audio : Eng by default
Subtitle : fre (French / Not Forced) by default ?

Thanks

**Comment by HaveAGitGat** [comment]
Hello, you can set default track using ffmpeg with:

`-disposition:a:0 default -disposition:a:1 none`

More info here:
https://video.stackexchange.com/questions/19634/mux-mkv-and-dts-file-change-default-audio-stream-and-language

Let me know if you'd like a plugin creator option for this and I can add it for the next update.

**Comment by Nonobis** [comment]
Hello,

Thanks ! I will try it.
A option in plugin creator would be great.

Could add also an option to keep only subtitle in specified language ?

Your soft is great by the way. :)

**Comment by HaveAGitGat** [comment]
Will do 👍

**Comment by HaveAGitGat** [comment]
I have created customisable plugins for moving audio and subtitles to default. I have tested the subtitle one and it works well, for example:
Config:
![image](https://user-images.githubusercontent.com/43864057/74002873-76fdea80-4968-11ea-9c7f-c262da2f410d.png)

Before:
![image](https://user-images.githubusercontent.com/43864057/74002850-63eb1a80-4968-11ea-848a-08c3538b21f1.png)

After:
![image](https://user-images.githubusercontent.com/43864057/74002908-93018c00-4968-11ea-95e6-42f46b1be734.png)

The same should happen with audio. You can test them later today when 1.104 is released.

**Comment by HaveAGitGat** [comment]
Also Migz is/has created plugins to only keep/remove certain subtitle and audio tracks based on language.

**Comment by HaveAGitGat** [comment]
1.104 now out. Added the 2 plugins:
Tdarr_Plugin_076a_re_order_audio_streams
Tdarr_Plugin_076b_re_order_subtitle_streams

**Comment by Nonobis** [comment]
Perfect, Thanks a lot :)

**Comment by kman3107** [comment]
@HaveAGitGat , Tdarr_Plugin_076a_re_order_audio_streams is pretty useful for setting default audio track on Chinese movies, as most of the ones I've gotten a hand on have the mistaken metadata saying that English is the original language. The only problem is that, if the audio track is already at the 0th index it won't do anything.

Is there any way to have the plugin set the chosen language as default even if it's already at the 0th index?
I can do this using a script,, but would be nice to have it in the workflow.
