### ISSUE TITLE
Tdarr_Plugin_a9hd_FFMPEG_Transcode_Specific_Audio_Stream_Codecs errors:  too many unbuffered packets

### ISSUE THREAD

**Issue by jeff47** [HaveAGitGat/Tdarr_Plugins#91]
I run into this error from time to time on this plugin.  Can be fixed by adding " -max_muxing_queue_size 9999 " to response.preset.

**Comment by HaveAGitGat** [comment]
Ok thanks, will add this in

**Comment by HaveAGitGat** [comment]
Added https://github.com/HaveAGitGat/Tdarr_Plugins/commit/d194a5326342d320a10fdad6b727df6215b77cab
