### ISSUE TITLE
Help with a plugin 10 Bits depth re-encode to 8 Bits.

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#93]
I have various h264 files, high 10@L4.1 format; with bit depth 10 bits.
The LG Oled plex app can't handle this format and I would like to understand if I 
a script can be created that only identifies these 10 bits depth files and re-encodes to the file to h264 on normal (8) bit.
Note, I don't want the script to re-encode all files, only the ones where it finds 10 bit depth.

Would such a thing be possible?

**Comment by HaveAGitGat** [comment]
```
 "ffProbeData": {
    "streams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main 10",
        "codec_type": "video",
        "codec_tag_string": "[36][0][0][0]",
```

Yes in the above hvec 10 bit file you can see the profile is Main 10 so you'd just need to do a similar profile check on your h264 files.

```
if(file.ffProbeData.streams[0].profile === 'profile name'){
   // do somethin
}
```
