### ISSUE TITLE
Bug: Tdarr_Plugin_076a_re_order_audio_streams.js sets correct 1st language, but doesnt apply the default correct

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr_Plugins#97]
This plugin does work to make a specific language to appear first as first audiostream, but the 'default' tag still stays on the original audiostream and is not set to the first. It seems the 'disposition' element of the instruction is not working as it should.

Edit-
To reproduce:
Take a video file, with multuple audiostreams in various languages and a default tag on a non-preferred language.
For example
Audiostream 1 English 2.0. Tagged as 'Default'
Audiostream 2 Dutch 2.0
Audiostream 3 English 5.1

After running the script:
Audiostream 1 Dutch 2.0 
Audiostream 2 English 2.0 Tagged as 'default;
Audiostream 3 English 5.1

Expected output: To have the first audiostream tagged as 'default' and the other audiostreams the default tag removed.

Thanks for your review

**Comment by HaveAGitGat** [comment]
I think this should fix it:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/213
